### ISSUE TITLE
Presence-absence dataset

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#10]
We want to be able to run examples of presence-absence as well as presence only models. It would be good to find either an online PA dataset we can easily link to (figshare etc.) or else bundle one with the package.

**Comment by goldingn** [comment]
Apparently we're not allowed to redistribute that, at least Dave Harris didn't dare when using it in his reproducible supplement to his MEE paper.

I tried with Bob O'H's rBBS package, but it's not really stable enough for us to depend on yet.

So I trawled Dryad and came up with [this dataset of the coffee-white stem borer in Zimbabwe](https://github.com/zoonproject/modules/blob/fc9dba23bc6e08953c86641049415cebf2a72c20/R/CWBZimbabwe.R)
