### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#103]
I'm just running through the zoon stable version installation instructions now and it's pretty ugly.
Since we've nailed almost all of the CRAN check issues (#92 notwithstanding) I think it's worth thinking about submitting to CRAN sometime soon.

I think it's probably feasible to do this in time for the workshop (once I've sorted #92) but there's a bunch of other stuff that needs doing for then too - what do you guys think?

CRAN prefer package updates to be 1-2 months apart, so we'd still use the github version for development, but hopefully most work will switch to modules before too long anyway.

**Comment by AugustT** [comment]
To me the priority is getting everything ready for the workshop, I don't see that the package needs to be on CRAN for this. Our time might be better focused on the other jobs that need to be done.

**Comment by timcdlucas** [comment]
I don't have too much of an opinion on this as a) I won't be doing much of the work and b) I have no experience submitting to CRAN.

Totally agree it would be easier for the workshop etc. if we could install from CRAN.

But given that we're still discussing breaking changes like the dot argument names in #49 it seems potentially early.

**Comment by goldingn** [comment]
Fair point. I've run the gauntlet a few times now and am willing to bear any Ripleying.

I guess we should see whether we have something fairly stable before the workshop and with enough time to sort it out

**Comment by AugustT** [comment]
Ha, I love a good Ripleying! I say we hold off, see where we get to next week

**Comment by goldingn** [comment]
yup, good call

**Comment by goldingn** [comment]
We're getting closer! I only get this note now:

```
* checking R code for possible problems ... NOTE
Found the following assignments to the global environment:
File ‘zoon/R/zoonHelpers.R’:
  assign("tmpZoonWorkflow", w, envir = .GlobalEnv)
```

so only issue #104 to go (though solving #113 would be good too)

**Comment by goldingn** [comment]
Issues #104 and #113 are both closed and I get no notes on `R CMD check -as-cran` on my machine.
Building on Travis on [shows the same](https://travis-ci.org/zoonproject/zoon) so it looks like we're just about ready to submit.

We still need to check against R-devel on unix and both R-release and R-devel on winbuilder.

**Comment by goldingn** [comment]
Self-assigning as I'm currently down as the maintainer so happy to push this through.

We should decide when we are at a stage to send though, since we will only want to update on CRAN once every few months.

**Comment by timcdlucas** [comment]
I can't think of many potentially breaking changes we have discussed as possibilities. 

Chain vs chain was one (I'm happy with Chain).

Are the arguments in `BuildModule` correct? Even if there's work to be done on the function, as long as the args are fine submitting to CRAN is fine. We can even add arguments later (as long as they have a default) because that's then not breaking. I think that's correct.

Other than that I'm not sure what we would want to implement before we submit. One consideration might be aiming to submit ~1 week before BES. Which would mean submit now or not at all until December.

**Comment by goldingn** [comment]
Or we submit now(ish) and then again in December?

Certainly worth waiting to fix `BuildModule` and any other bugs first though, good point

**Comment by timcdlucas** [comment]
Yes that's what I meant by now. Now and in December. Seems best plan to me.

**Comment by goldingn** [comment]
:+1:

**Comment by goldingn** [comment]
So holding off until the three current bugs (BuildModule: #158 #82 and ChangeWorkflow: #57 ) are fixed, then fully checking and submitting to CRAN shortly.

**Comment by AugustT** [comment]
Great work guys. Hoping my diary is going to clear up towards the end of this week so I can get some time in on this. Support the idea of submitting soon.

**Comment by goldingn** [comment]
Great! We should decide on who the named maintainer should be before our first submission as we probably want to keep that consistent across future releases.

**Comment by AugustT** [comment]
I think I should be the named maintainer since I'm the one who should be doing most of the ground work over the next year. However for now I'm happy to keep my junior position on the author list.

**Comment by goldingn** [comment]
Sounds good to me, happy to unassign myself from this issue :)

The author order is totally up for debate too, I guess it ill change over time and I don't see a problem with that being different between CRAN submissions.

**Comment by AugustT** [comment]
Getting close now!

**Comment by goldingn** [comment]
Looks like all of the other issues have been cleared @AugustT!

What's the plan - submit now, or are there more tweaks you want to make?

**Comment by AugustT** [comment]
Hmm, I'm pretty much happy. I think it might be good to tweak the build module code to enforce some of the module standards, some of which are more clear since the wire-frame but more might come out of our chat with Gef.

With that done I think I can live with all the other issues that are on here. We could do a CRAN update before Christmas.

**Comment by goldingn** [comment]
Yeah, I think they'll be OK  with a short gap on a new package, and if we tell them there's a reason we need todo it then.

**Comment by AugustT** [comment]
Submitting

**Comment by timcdlucas** [comment]
Whooop

**Comment by goldingn** [comment]
Once this is accepted on CRAN, we should update the readme with new installation instructions. Also we can add the CRAN badge (also mentioned in #152, but here again because it's cool):

[![cran version](http://www.r-pkg.org/badges/version/zoon)](http://cran.rstudio.com/web/packages/zoon)

**Comment by AugustT** [comment]
OK. 

Some fixes on the first submission. Apparently we have to import `graphics`, `utils` and `methods` functions ?!

Testing updates on Travis then I'll put it back in.

**Comment by goldingn** [comment]
Weird. I knew they wanted loads of these packages to have importFroms, but that wasn't flagged on R-devel, where it normally comes up: https://travis-ci.org/zoonproject/zoon/jobs/95203074#L2489

**Comment by AugustT** [comment]
Yeah, I was supprised that they came back with issues that had not been flagged in our checks. For reference here is the first set of comments which I have addressed.
```
Found the following (possibly) invalid URLs:
   URL: https://cran.r-project.org/web/packages/gam/index.html
     From: inst/doc/Building_a_module.html
     Status: 200
     Message: OK
     CRAN URL not in canonical form
   The canonical URL of the CRAN page for a package is
   https://cran.r-project.org/package=pkgname


* checking R code for possible problems ... NOTE
Boxed2: no visible global function definition for 'strwidth'
Boxed2: no visible global function definition for 'segments'
Boxed2: no visible global function definition for 'rect'
BuildModule: no visible global function definition for 'is'
BuildModule: no visible global function definition for 'capture.output'
ChangeWorkflow: no visible global function definition for 'sessionInfo'
DisplayModuleHelp: no visible global function definition for
   'browseURL'
DownloadQuietly: no visible global function definition for
   'download.file'
GetCex: no visible global function definition for 'strwidth'
GetMaxEnt: no visible global function definition for 'browseURL'
GetPackage: no visible global function definition for
   'install.packages'
ModuleLabels: no visible global function definition for 'strwidth'
ModuleLabels: no visible global function definition for 'segments'
RerunWorkflow: no visible global function definition for 'sessionInfo'
ZoonFigshare: no visible global function definition for 'browseURL'
plot.zoonWorkflow: no visible global function definition for 'plot.new'
plot.zoonWorkflow: no visible global function definition for 'par'
plot.zoonWorkflow: no visible global function definition for 'plot'
plot.zoonWorkflow: no visible global function definition for 'rect'
workflow: no visible global function definition for 'sessionInfo'
Undefined global functions or variables:
   browseURL capture.output download.file install.packages is par plot
   plot.new rect segments sessionInfo strwidth Consider adding
   importFrom("graphics", "par", "plot", "plot.new", "rect", "segments",
              "strwidth")
   importFrom("methods", "is")
   importFrom("utils", "browseURL", "capture.output", "download.file",
              "install.packages", "sessionInfo") to your NAMESPACE (and ensure that your DESCRIPTION Imports field contains 'methods').
```

**Comment by goldingn** [comment]
Yeah, odd. I wonder if something changed in R-builder?

**Comment by AugustT** [comment]
Particularly annoying as I don't seem to have a way to check that these errors have been corrected by my edits (though I'm fairly sure they have). New version submitted.

**Comment by AugustT** [comment]
Whoops, looks like the changes they has requested are causing us some issues...

Not 100% sure but I have changed the NAMESPACE file to include importFrom(graphics, plot). This comes after import(raster) and I think this stops plot.raster working...
```
work1 <- workflow(occurrence = UKAnophelesPlumbeus,
                  covariate  = UKBioclim,
                  process    = OneHundredBackground,
                  model      = LogisticRegression,
                  output     = PrintMap)

Caught errors:
Error in as.double(y): cannot coerce type 'S4' to vector of type 'double'
```

It looks like I can fix this by adding 'GetPackage(raster)' to the module... not ideal

**Comment by goldingn** [comment]
That's quite weird, I wouldn't expect it to have that effect. Is that where that error message comes from?

**Comment by AugustT** [comment]
As far as I can tell the error is produced because the call to `plot` in both `PrintMap` and `SurfaceMap` does not get through to `raster` resulting in the above error. The error message comes from the output module and cannot be recreated interactively.

**Comment by AugustT** [comment]
There is something about this issue here: http://stackoverflow.com/questions/14437750/namespace-issue-with-raster-package-plot-function

And a suggestion here that having raster in depends fixes the issue (but raster is already in depends).
https://github.com/ropensci/paleobioDB/issues/13

Have to confess some of the search path bits are over my head.

I'm going to implement explicit GetPackage calls for raster in the 2 offending output modules which might fix the issue

**Comment by AugustT** [comment]
That did not fix the issue. I think it is a search path issue as if you load the modules first they do work.

```
# this works
LoadModule('PrintMap')

work1 <- workflow(occurrence = UKAnophelesPlumbeus,
                  covariate  = UKBioclim,
                  process    = OneHundredBackground,
                  model      = LogisticRegression,
                  output     = PrintMap)
``` 

If I remove the importsFrom(graphics, plot) from the namespace file then the error goes away, but the folks at CRAN want it there.

If I replace importsFrom calls for graphics with a single imports call for graphics the error returns.

I'm a little stuck with this one. I see 2 options

1. Find a way to get the raster plotting to work with graphics plot imported, I'm out of ideas for the moment
2. Argue with CRAN to not have import graphics, plot - which might work because it is only a note?

I assume my last submission will come back from CRAN with error trying to build vignettes (past my checks... not sure how!)

**Comment by AugustT** [comment]
In a fit of desperation I deleted all my libraries and reinstalled. The issue persists.

**Comment by goldingn** [comment]
Frustrating! Will take a look tomorrow and see if I can find a way through

**Comment by goldingn** [comment]
Longer-term I think that implementing https://github.com/zoonproject/zoon/issues/84#issuecomment-131869786 would solve this, and similar future problems, so it's worth thinking about whether we want to go down that route next year.

But obviously there's no time to do that this week... I'm stumped, I can't think of a quick way to get around this, so suggest we explain our reasoning to not doing `importFrom` for this package to Uwe.

Worth mentioning that we are thinking about refactoring to avoid the issue in future versions, but that it is far from trivial.

**Comment by AugustT** [comment]
New comments:
```
We get

* checking R code for possible problems ... NOTE
plot.zoonWorkflow: no visible global function definition for ‘plot’
Undefined global functions or variables:
  plot
Consider adding
  importFrom("graphics", "plot")
to your NAMESPACE.

Pls fix.

Also,

* checking tests ... [12m/14m] OK
  Running ‘test-all.R’ [12m/14m]

is really excessive: do you really need to ship all these tests for regular checking?

Best
-k
```
I'll .Rbuildignore most of the tests and try again our plea not to do the import.

**Comment by AugustT** [comment]
I will also change the call to `plot` in `plot.zoonWorkflow` to `graphics::plot`

**Comment by AugustT** [comment]
Done
