### ISSUE TITLE
tmpZoonWorkflow changes global workspace (for CRAN sub)

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#104]
- Packages should not modify the global environment (user’s workspace).
https://cran.r-project.org/web/packages/policies.html

I struggled to think of good places to save a workflow on a crash when I wrote this. But didn't know this was disallowed.

**Comment by goldingn** [comment]
Cool. We discussed this the other day and think that it should be no problem to return the aborted workflow to the same object the user was assigning to.
I.e. `w1` in `w1 <- workflow(...)`

Can you remeber why we didn't do that in the first place?

**Comment by timcdlucas** [comment]
I couldn't work out how. 

The problem was to have a proper `stop()` call (if people are using workflows inside other functions, we want to fully error out) and return an object from the function.

If the call is w <- workflow()

You can't do

    assign('w', tmpWorkflow, envir = .GlobalEnv)
    stop('workflow broke')

because a function doesn't know where it is assigning its output to.

You can't do

    return(tmpWorkflow)
    stop('workflow broke')

Because the `return()` prevents the `stop` being run.

**Comment by goldingn** [comment]
Riiight... that makes sense.

I guess if we did want to assign to the user's object, and not assign to the global namespace (which it seems like we have to) then this behaviour should really be a warning...

**Comment by AugustT** [comment]
Can you use `on.exit` ?

**Comment by timcdlucas** [comment]
People don't read warnings though. And again, if people are running 20 separate workflows or something, if it breaks it should error, not just give a warning and carry on running.

An option is to save a .RData to tmp or something. 

I also looked into saving tmpWorkflow to the zoon environment, but apparently that is impossible.

I'll have a think about `on.exit`.

**Comment by AugustT** [comment]
I'm not 100% about on.exit but I think you could write use a function like your SaveandExit() inside on.exit so that when it hits the error, the error is reported then the function runs on the workflow that was created and that result is returned.... maybe

**Comment by AugustT** [comment]
This works:
```R
bg <- function(x){
  
  on.exit(return(x))
  
  while(TRUE){
    
    x <- x + 1
    if(runif(1)>0.8) stop('my error')
    
  }
}
```

```
> out <- bg(5)
Error in bg(5) : my error
> out
[1] 8
```

**Comment by goldingn** [comment]
:+1:
