### ISSUE TITLE
workflow function name

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#105]
Probably should have discussed this earlier.

Is workflow the best name for the main function? 

- It is not SDM specific
- It is not zoon specific
- It does not fit the google style guide (should be Workflow).
- It is a little long.

Alternatives:
1. Zoon
2. Workflow
3. SDM

**Comment by AugustT** [comment]
Workflow is the only one that describes what the function does (zoon having no relevant meaning and SDM being only a part of what it does).

I have no problem with workflow (I know capitalisation is in the Google style guide but I just can't get used to it!)

**Comment by goldingn** [comment]
Yeah, UpperCamel case weirds me out.

If we want to change the style guide (I prefer lowerCamel), then before the workshop is probably the best time...

workflow seems fine to me

**Comment by goldingn** [comment]
I think we're sticking with workflow for now, so closing this
