### ISSUE TITLE
Duplicate LocalRaster modules

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#110]
We have two modules, LocalRaster and LocalRaster2, whose descriptions are the same. Are these duplicates? @timcdlucas

**Comment by AugustT** [comment]
I realise the code is subtly different

**Comment by timcdlucas** [comment]
I think LocalRaster2 is probably the one I tried to write at the workshop when noone could read their data in. 

I'm not sure which one is better. But there's only meant to be one (that works properly).

**Comment by goldingn** [comment]
LocalRaster2 had less info and an apparent bug, but was otherwise identical, so I just went and deleted it
