### ISSUE TITLE
ResponseCurve module with presence absence data

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#111]
Currently I get this with CWBZimbabwe:

![image](https://cloud.githubusercontent.com/assets/4450731/9657166/8b2505da-5236-11e5-8b86-2edfe1006f64.png)

It should detect whether there is background/absence data and plot accordingly

**Comment by AugustT** [comment]
Also there is no x-axis labels... but that might have been in the missing plot

**Comment by goldingn** [comment]
Also it errored out:

```
> work2 <- workflow(occurrence = CWBZimbabwe,
+                   covariate = Bioclim(extent = c(32, 34, -21, -18),
+                                       res = 2.5),
+                   process = NoProcess,
+                   model = LogisticRegression,
+                   output = ResponseCurve(cov = 1))  # <- stick something in here
Caught errors:
Error in hist.default(covar[back_idx], breaks = 50, xlim = c(covar_min, : character(0)


Error: Stopping workflow due to error in output module.
 Workflow progress stored in object 'tmpZoonWorkflow'.
In addition: There were 21 warnings (use warnings() to see them)
```
(warnings are about rank deficiency in the model)

**Comment by goldingn** [comment]
those x axis labels are missing in a larger version too, so need fixing

**Comment by goldingn** [comment]
These are fixed in [a PR to modules](https://github.com/zoonproject/modules/pull/17)
