### ISSUE TITLE
add type option to SpOcc

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#119]
This will allow users to carry out the target group background approach of Phillips et al. (2008) (which is something I'd like to cover in the workshop) by chaining a species with `type = 'presence'` and multiple species with `type = 'background'`

**Comment by AugustT** [comment]
:+1:

**Comment by timcdlucas** [comment]
In my mind this is either a covariate or process action and should therefore have a separate (although almost identical) module.

Obviously just need to get stuff running for the workshop, so happy to not worry about this for now.

**Comment by goldingn** [comment]
Yeah, that's a fair point. Have implemented it now, and will move to a separate module later
