### ISSUE TITLE
Handle target group background data in a process module

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#121]
[Phillips et al](http://www.cs.princeton.edu/~mdudik/PhillipsEtAl09.pdf)'s. target-group background method is a handy way of accounting for reporting bias in occurrence data, when fitting a presence-only SDM. Basically this just involves selecting several other species which are likely to be subject to a similar spatial pattern of reporting bias, and using occurrences of those species as the background (aka pseudo-absence) points in the presence-only SDM analysis.

It is currently possible to  implement this in zoon by chaining `SpOcc` occurrence modules (implemented as in #119) like so:

```r
w <- workflow(occurrence = Chain(SpOcc(species = 'Myotis daubentonii',
                         extent = c(-1, 0, 51, 52),
                         type = 'presence')),   # <- the species we're interested in
                 SpOcc(species = 'Pipistrellus pipistrellus',
                         extent = c(-1, 0, 51, 52),
                         type = 'background'),   # some other species as background points
                 SpOcc(species = 'Plecotus auritus',
                         extent = c(-1, 0, 51, 52),
                         type = 'background')),
            ...)
```

However this is likely to be confusing when introducing the approach to new SDMers, since the background point selection is normally done as a process module, and they're not actually interested in the occurrences of these other species.

Instead, it would be great to have a target-group-background process module which takes as input a list of species and extent and returns a bunch of background points, with a pattern like this:

```r
TargetGroupBackground(species_list = c('Pipistrellus pipistrellus', 'Plecotus auritus'), extent = c(-1, 0, 51, 52))
```

**Comment by AugustT** [comment]
This issue is unclear. What is *"target group background data"* and what is meant by *"handle"*? @goldingn can you clarify the issue (ideally edit you first comment). Or assign to yourself and then I will ignore it in blissful ignorance, knowing it is in your capable hands!

**Comment by goldingn** [comment]
edited :)

**Comment by AugustT** [comment]
Great, thanks for clarifying this one!

Sound like a sensible approach to implementing their method. I would add that the user might want to add their own data so it would be great to accommodate a `LocalOccurrence` type approach as well. 

Actually what about if you could include a call to an occurrence module

```r
TargetGroupBackground(OccModule = SpOcc(species = 'Plecotus auritus',
                                         extent = c(-1, 0, 51, 52),
                                         type = 'background'))

TargetGroupBackground(OccModule = LocalOccurrenceData('mydata.csv'))

TargetGroupBackground(OccModule = Chain(LocalOccurrenceData('mydata.csv'),
                                         SpOcc(species = 'Plecotus auritus',
                                         extent = c(-1, 0, 51, 52))))
```

Everything loaded here would be treated as background. Do you think this is over complicating it? I like it because it is more generalisable.

**Comment by goldingn** [comment]
I do like that. Another approach would be to make it a thin wrapper, and enable module writers to call other modules within theirs. I think that was discussed previously and will reduce code duplication and possibly licencing issues (can call someone else's module without having to copy the code and attribute to the original author)

**Comment by AugustT** [comment]
FYI I'm close to having this done

**Comment by goldingn** [comment]
:+1:

**Comment by AugustT** [comment]
The initial issue has been addressed. The module is called `TargetGroupBackground`
