### ISSUE TITLE
MOAR MODELS

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#122]
We could do with a variety of different, commonly used statistical models, including BRT and GAM for the workshop practicals

**Comment by timcdlucas** [comment]
I was thinking that a [caret](http://topepo.github.io/caret/modelList.html) module might be the easiest way to do this. 
But we'd want to think carefully about the API so probably just separate modules for the common models as mentioned is best for the workshop.

For models with tuneable parameters, I imagine we want those to be automatically selected using cross validation (a separate cross validation within the total cross validation). So these modules might not be totally simple.

**Comment by goldingn** [comment]
I've just done an mgcv GAM one (had to edit all of the output module prediction handling to do it) which I'll upload shortly.

For the same reasons, I can't do a BRT one without implementing the predict mechanism in #84, or editing the output modules in a really awful way, since predict.gbm has an argument `n.trees` with no default...

**Comment by goldingn** [comment]
I've now added a GBM (AKA BRT) one as well as a standalone MaxEnt one - both of these using `dismo`.

The MaxEnt one requires users to put the .jar file in a different place, but the helpfile explains it. I also have had rJava trouble on RStudio in OSX, which appears to be a known issue. I have a workaround if that's ever needed.

**Comment by goldingn** [comment]
I hereby closeth this
