### ISSUE TITLE
GBM breaking

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#130]
Just reinstalled zoon from github and GBM doesn't seem to be working.

    work1 <- workflow(occurrence = UKAnophelesPlumbeus,
                      covariate  = UKAir,
                      process    = OneHundredBackground,
                      model      = GBM,
                      output     = PrintMap)
    
    Caught errors:
    Error in checkForRemoteErrors(val): 3 nodes produced errors; first error: incorrect number of  dimensions

I'm getting 8 `Loading required packages: stats` messages which I assume is the package loading in each of my 8 cores. I'm a bit confused how R knows how many cores I have. And we probably want to be able to set the number of cores zoon uses, but that's a separate issue.

**Comment by goldingn** [comment]
this issue is already the 8th hit on google as I try to debug. Google is terrifying.

**Comment by goldingn** [comment]
The current CRAN version of gbm has a bug whereby one-predictor models fail when fitted with cross-validation. The Github version (https://github.com/gbm-developers/gbm) works just fine. Here's an MRE:

```r
# pick your version:
# install.packages('gbm')
# devtools::install_github('gbm-developers/gbm')

library(gbm)

y <- sample(0:1, 100, replace = TRUE)
df <- data.frame(x = rnorm(100))

m <- gbm(y ~ x,
         data = df)
# works fine

m <- gbm(y ~ x,
         data = df,
         cv.folds = 3)
# fails with CRAN version
```

Since we're CRAN-only, I'm going to avoid doing CV for now and use out-out-bag sample to get the optimal number of trees

**Comment by goldingn** [comment]
closed by [this PR](https://github.com/zoonproject/modules/pull/27)
