### ISSUE TITLE
PredictNewArea - Help and Plot

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#134]
improve the help so that the meaning of extent is clear (see Bioclim for example)

Throw nice error if extent is not provided

Make a plot output by default (see printmap)

**Comment by AugustT** [comment]
Addressed in https://github.com/AugustT/modules/commit/1aeb599d368c9497bdbefcd3221e48fc75dff465

**Comment by timcdlucas** [comment]
This is all great work by the way @AugustT. Really tightening up the package.

**Comment by AugustT** [comment]
![image](https://cloud.githubusercontent.com/assets/3987564/13141177/d071512c-d62d-11e5-9c62-7297dc483a85.png)
