### ISSUE TITLE
point details in InteractiveMap

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#140]
It should be possible to display, when clicking on a point, features such as type (i.e. presence or background) and fold. Which might be handy.

**Comment by AugustT** [comment]
Partly addressed in #132

**Comment by AugustT** [comment]
Clicking on a point now shows type, lat, long, fold and value. 

See https://github.com/AugustT/modules/commit/da8249513debd6d7167e9b9cf8604c4377f82320
