### ISSUE TITLE
NAs in spocc

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#142]
work6 <- workflow(occurrence = SpOcc(species = 'Monomorium pharaonis',
                                         extent = c(-30, 30, -0, 90), databases = 'antweb'),
                      covariate = Bioclim(extent = c(-180, 180, -90, 90),
                                          res = 10),
                      process = OneThousandBackground,
                      model = LogisticRegression,
                      output = InteractiveMap)

    243 results available for query.
    Caught errors:
    Error: not compatible with requested type

I'm not sure if it's antweb, or because of NA's in the latitude, longitude columns, but these columns are class "character" in `raw` in SpOcc.

    raw <- occ2df(occ(query = 'Monomorium pharaonis', 
      geometry = c(-20, 20, 0, 70), from = 'antweb', limit = 1000))

**Comment by goldingn** [comment]
closed by [recent pr](https://github.com/goldingn/modules/commit/8f0e4818cfd0859cd545aa765d869c80b5a469bc)
