### ISSUE TITLE
write a zoon docker image

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#144]
With an OS and R packages that safely handle all zoon modules - this would lower the technical barrier to using zoon and could be used for future workshops, for online/gui interface and for testing

**Comment by goldingn** [comment]
Just had a play with docker on my mac - fairly easy to set up!

In theory we'd only need to take an existing dockerfile and add the commands to install additional software (gdal, java) and pre-install R packages.

We could then add the dockerfile to dockerhub where an image would be build which can be easily downloaded.

If we were to base the image on one of rocker's images which include rstudio, then people will be able to run interactively in a familiar environment in their browser.

We could also easily set up an RStudio server for attendees to use in a course - they'd each have their own login details, server space etc.

### MaxEnt

The [MaxEnt website](https://www.cs.princeton.edu/~schapire/maxent/) says:
>... The software may not be further distributed. ... 
So we couldn't put the jar file in the image.
We could probably define a function to allow users to ping the file to the container and put it in the correct place however.

**Comment by AugustT** [comment]
I'm not sure this is feasible @goldingn. Given the number of modules we have (and obviously the thousands we will have in the future) maintaining a docker image with all the packages required for all the modules seems unrealistic

**Comment by goldingn** [comment]
Yup, I agree. Closing.
