### ISSUE TITLE
Split zoon.r script

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#151]
This should be split in to the component scripts so it is more transparent. (i.e. there is no workflow.R script which seems odd to an outsider)

**Comment by AugustT** [comment]
Thanks @timcdlucas

**Comment by timcdlucas** [comment]
I didn't do a pull request for this yet. Started doing the accessor functions and got distracted. I'll finish them at some point and PR.

**Comment by AugustT** [comment]
Great :)
