### ISSUE TITLE
Here are some additional badges we can add to the readme 

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#152]
Though we probably don't want to add them until they show something of use.

[![cran version](http://www.r-pkg.org/badges/version/zoon)](http://cran.rstudio.com/web/packages/zoon) the cran version number and link to cran page (RStudio version)

[![rstudio mirror downloads](http://cranlogs.r-pkg.org/badges/zoon?)](https://github.com/metacran/cranlogs.app)  monthly downloads from the RStudio CRAN mirror

[![Coverage Status](https://coveralls.io/repos/zoonproject/zoon/badge.svg?branch=master)](https://coveralls.io/r/zoonproject/zoon?branch=master) code test coverage via coveralls

To see the markdown for copy-pasting, click edit (little pencil in the top right) on this message.

**Comment by goldingn** [comment]
coveralls button switched to codecov   [![codecov.io](https://codecov.io/github/zoonproject/zoon/coverage.svg?branch=master)](https://codecov.io/github/zoonproject/zoon?branch=master)   and added to README.

So just the CRAN ones to add when we've got it over there

**Comment by goldingn** [comment]
When this is on CRAN (and indexed and downloaded/cited a bit) we can stick up this depsy badge
`[![Research software impact](http://depsy.org/api/package/cran/zoon/badge.svg)](http://depsy.org/package/r/zoon)`

It should look a bit like this one for rnbn: [![Research software impact](http://depsy.org/api/package/cran/rnbn/badge.svg)](http://depsy.org/package/r/rnbn)

**Comment by AugustT** [comment]
neat
