### ISSUE TITLE
Tests for modules

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#159]
To spot silly module bugs, help others to write modules, and facilitate uploading to a community module repo we need to define tests to enforce the module I/O rules.

These should:

- [x] Check the module has all of the required arguments for it's module type
- [x] Check all parameters are documented
- [x] Check the module returns an object of the correct structure, and with elements matching required structure (down to dataframe column class checking, RasterLayer projection checking) 
  - [x] Occurrence
  - [x] Covariate
  - [x] Process
  - [x] Model
  - [x] Output
- [x] be incorporated into a `CheckModule` function which is both visible to module developers and used in the community repo etc.
- [x] Check that the module survives a range of standard workflows representing different use cases (chains, lists, cross validation etc.)
  - [x] Occurrence
  - [x] Covariate
  - [x] Process
  - [x] Model
  - [x] Output
- [ ] Automatically added @return field
- [x] section version and date when (onRepo == TRUE)
- [x] packages are documented

I think this will be crucial for getting `zoon` ready for wider use. What do you guys think of this - anything else we should test?

**Comment by timcdlucas** [comment]
Sounds good and I cant think of anything else that needs testing.

Wonder if its worth asking for abasic example of module use which can then be one of the tests.

I guess some test of whether modules work with presence absence, presence only and adundance might be useful.

**Comment by AugustT** [comment]
- Check that the module help documentation covers all of the require fields

**Comment by goldingn** [comment]
Have we defined what the required fields are yet? If so it would be great to let Gef know.

I'd imagine:

`@title`
`@name`
`@description`
`@details`
`@value`
`@family`
`@author`
`@param` (for all arguments)

any others?

**Comment by goldingn** [comment]
Related to this, I found the bit in `roxygen2` that does the parsing of oxygen comments. So this function should help with the tests:

```r
RoxyFile <- function (file) {
  roxygen2:::parse_file(file, environment())[[1]]
}
```
e.g.:
```r
docs <- RoxyFile('https://raw.githubusercontent.com/zoonproject/modules/master/R/BiasBackground.R')
str(docs)
```
```
List of 8
 $ param       :List of 2
  ..$ name       : chr ".data"
  ..$ description: chr "\\strong{Internal parameter, do not use in the workflow function}.\n\\code{.data} is a list of a data frame and a raster object"| __truncated__
 $ param       :List of 2
  ..$ name       : chr "bias"
  ..$ description: chr "Raster with cells giving the relative probability of a background record being sampled there."
 $ param       :List of 2
  ..$ name       : chr "n"
  ..$ description: chr "Positive integer giving the number of background points required."
 $ author      : chr "Nick Golding"
 $ name        : chr "BiasBackground"
 $ family      : chr "process"
 $ introduction: chr "BiasBackground: Generate background data using a bias grid\n\nThis process module genereates a sample of background records acc"| __truncated__
 $ srcref      :List of 2
  ..$ filename: chr "https://raw.githubusercontent.com/zoonproject/modules/master/R/BiasBackground.R"
  ..$ lloc    : int [1:8] 22 1 68 1 1 1 22 68
```

Apparently this combines the title and description into introduction though, so this could be improved on...

**Comment by timcdlucas** [comment]
Is @value the output? As that is almost totally constrained (except on output modules) it seems unnecessary. 

@email should be mandatory.

**Comment by AugustT** [comment]
I think it would be good to have @return. This can be added automatically for all modules except output modules where the user will need to add it in.

**Comment by AugustT** [comment]
I dont think @value is a tag. @return becomes `value` in the .rd file

**Comment by AugustT** [comment]
How are we going to take version numbers?

There is a @note tag that we could write to in a formulaic way. For example when the module is submitted to the repository

@note version: 1.0, submissionDate: 2015-10-07

**Comment by goldingn** [comment]
I think there are also `@section` tags which are generic, so:

```r
#' @section version 1.0
#' @section submitted 2015-10-07
```

**Comment by AugustT** [comment]
@section is better as it names the section

**Comment by AugustT** [comment]
Can we write generic tests for the module repo on Github using testthat. The tests would simply loop through all the modules by type performing occurrence tests on occurrence models etc... using the criteria above and by running them on a couple of workflows. Then we could set up Travis on it and this would help to alert us to issues. with modules.

Similarly with these tests written we could include them in BuildModule or on submission to the repo.

**Comment by goldingn** [comment]
Yes, I think that would be a great idea.

As soon as we have some skeleton module tests written into zoon we can set up the loop-based test-suite for the modules and write tests against codecov. I'd be happy to set up the Travis/codecov side of things again.

One thing that crossed my mind, do we want to use `testthat`/`assertthat` in the module test functions in `zoon`? If so it would mean extra dependencies (though not the full hadleyverse), but might be easier to write.

**Comment by AugustT** [comment]
It would be great if you could handle the Travis /codecov bit as that will be much quicker than me doing it (However I definitely need to implement these in the other packages I have on GitHub so might borrow your code!).

I don't have any issue with a dependency on `testthat`. I think the benefits outweigh the costs

**Comment by goldingn** [comment]
Cool, sounds good.  Will set those up now - code coverage will be 0% to start with, but that's OK :)

**Comment by AugustT** [comment]
Great, can you add those little icons to the readme?

**Comment by timcdlucas** [comment]
Are these tests going to require default values for non-internal arguments? I know at least some don't have those (seemed weird to have a default machine learning method for example.)

**Comment by AugustT** [comment]
That is a good point. If defaults are not assigned then it's going to be very difficult to run an automated test. 

As an alternative it could be made mandatory to include an example which could be run as a test.

**Comment by goldingn** [comment]
Hmmm... I think we should enforce default values for non-internal arguments for that reason. I know it looks weird in some cases but we need something that will run through basic tests - surely all modules should *just work* when plugged into others?

(will add readme badges now...)

**Comment by timcdlucas** [comment]
I `spocc` is a better example of a weird module. What is a default species? But I don't mind. In a way having a default is a good way to give an example. Instead of describing a parameter as a string, having a default string does that for you.

**Comment by goldingn** [comment]
Yeah, that's a good point. It will be a nightmare to test occurrence or raster modules where we can't automate the inputs.

I think we need to enforce defaults for all modules then, and only ever test on those defaults (unless additional examples are provided).

**Comment by goldingn** [comment]
I've opened issue #210 to fix these for existing modules

**Comment by AugustT** [comment]
I'm not sure @details should be a required field. I think description should be but @details could be optional.

**Comment by AugustT** [comment]
Author and email should be combined in this format

```
#' @author Karl W Broman, \email{kbroman@@biostat.wisc.edu}
```

**Comment by AugustT** [comment]
Got the module testing started, thought I would share this with you:
```
General module tests : Loading required package: bitops
......1...2..3...4..5...6..7...8..9..........a..b...c..d......e...f..g...h..i...j..k...l..m...n..o...p..q.................r..s...t..u...v..w...x..y...z..A...B..C......D..E...F...G..H......I...J..K...L..M...N..O...P..Q...R..S...T..U...V..W...X..Y...Z..F...F..F
```
It ran out of letters! haha

**Comment by goldingn** [comment]
Ha!

Cool, I'm happy with details being optional. It means some modules will only have one line saying what they do, but at this stage lowering the bar for contributions is probably more important.

**Comment by AugustT** [comment]
@goldingn one of the requirement at the top here is RasterLayer projection checking. Do we want the projection to be `+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0`, or is there some flexibilty?

**Comment by goldingn** [comment]
I hesitate slightly at only allowing WGS84 - it would be nice if zoon could handle different coordinates systems. However that would necessitate checking/enforcing systems for both covariate and occurrence data though, and probably some internal conversion between them.

So for now I think it would be sensible to enforce WGS84 with that proj4 string, and we could add handling of different systems as a feature to a future version of zoon.

**Comment by AugustT** [comment]
Sorry, I'm a bit naive about proj4 strings and raster objects. When testing some of the cov modules their proj4 strings do not match the one above, eg UKAir has simply `+proj=longlat +ellps=WGS84`. This is presumably fine?

Also if you look at the raster stack returned by NCEP module this has no projection information (that I can find) and so also fails my tests. Presumably this *is* lat long data and so still works and we just need to update the module to make the projection explicit?

**Comment by goldingn** [comment]
Yeah, wgs84 is the default, so the version with fewer arguments is the same and the one without projection is assumed to be the same.

For NCEP, yes we should define the projection in the module.

Maybe `raster::compareCRS` compare the UKAir one sensibly?

**Comment by goldingn** [comment]
I think you've completed some more of these now @AugustT ?

**Comment by AugustT** [comment]
Implementing the workflow checks has not been as easy as you might think due to environments in testing and annoying CRAN requirements. I had to create a new occurrence module that would allow me to create random points anywhere in the world, its rubbish for anything other than testing really.

**Comment by AugustT** [comment]
changes coming in a PR soon

**Comment by goldingn** [comment]
Cool!

**Comment by AugustT** [comment]
Closing as testing is now implemented. I decided against the requirement for a `@return` tag
