### ISSUE TITLE
bump up test coverage

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#160]
We're at 55% at time of writing, with some files at very high coverage and others at much lower coverage: https://codecov.io/github/zoonproject/zoon/R?ref=e00b3b9f411b285821d17f57ddc51d96e0935b33

I suggest we aim for 90% coverage before closing this issue

**Comment by AugustT** [comment]
Neat extension

**Comment by AugustT** [comment]
The libcurl dependent tests are currently commented out. With these in we are at 89%

**Comment by AugustT** [comment]
so close!

**Comment by AugustT** [comment]
Done :)
