### ISSUE TITLE
Nice HTML report

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#173]
It would be great if we could combine the model call and all of the outputs in an HTML report.

It could recapitulate the call (using Greg's plot method), embed images created by each module (we'd set a plotting device for each output module execution), embed any html widgets (e.g. the output of `InteractiveMap`), report any text dumped to the console by modules (e.g. by `PerformanceMeasures`) and provide links to any objects returned, held in a temporary directory (e.g. RData files for rasters, other outputs).

This would document a run and solve some of the users' confusion about where the outputs go (looking in a nested list in the workflow object was weird to many). The html could be returned in a browser as part of the print method for example.

How does this sound?

**Comment by Pakillo** [comment]
Sounds great! I'd give the option to produce as PDF too

**Comment by goldingn** [comment]
Cool, something knitr-y sounds like a good option then. Not 100% we could embed htmlwidgets that way, but in any case we could just link from the doc to a browser

**Comment by AugustT** [comment]
pdf would require the user to install latex I think so I would prefer to focus on HTML. I think this is a great idea though.

It would be best if this could be built solely from the workflow object, I wonder if that is possible?? This would save messing around with devices.

**Comment by Pakillo** [comment]
> pdf would require the user to install latex I think so I would prefer to focus on HTML

Yes, you're right. And one could always print the html as pdf from the browser...

**Comment by goldingn** [comment]
Yup, could have pdf as an option for those with latex, html as a default.

We could re-create plots for a report from a workflow object by re-running output modules, and capturing their side-effect plots (which would require setting a graphics device anyway).

I think I'd rather have the report as *the* way of getting those plots to user though. I.e. set the graphics device to save all side effect plots when running the workflow, then give them back to the user in this report.

**Comment by AugustT** [comment]
If you put a device around your output model (as an example) how do you guarantee that you capture the output in a way that can be placed into a knitr/markdown document? The module could print stuff to console, could plot something, or display in the browser (or feasibly all three!?). We would need to capture all of these things.

**Comment by AugustT** [comment]
Closing as we have created an HTML report. Whether it is 'nice' is up for debate.
