### ISSUE TITLE
scrubr data cleaning

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#174]
[scrubr](https://github.com/sckott/scrubr)

Be good to make a data cleaning module.

scrubr looks nice but isn't on CRAN yet. Might be easier to copy code (and attribute) rather than call package at this stage.

**Comment by goldingn** [comment]
yeah - maybe splitting into separate steps would be handy (e.g. removing impossible coords as one, moving in-sea points to the nearest land mass as another etc.)

**Comment by timcdlucas** [comment]
Wasn't sure whether it's better to have separate modules or one module which switches for each step. Certainly need to control what exact steps should be used.

One module is easier for users. Multiple modules is easier for others to add data cleaning modules without having weird things like "these four steps from this one module and then these three other modules."

**Comment by goldingn** [comment]
yup, raises a question about whether we should allow meta-modules (essentially wrapping chains as modules) which would allow people to release specific combinations of processes.

**Comment by goldingn** [comment]
see #176 to discuss meta-modules. I think this would be the best of both worlds here.

**Comment by goldingn** [comment]
@timcdlucas is this issue solved by the `Clean` module?

**Comment by timcdlucas** [comment]
Yes. It's not  very comprehensive though. Basically removes impossible lat longs and (0, 0) and that's about it I think.

Feel this might be a model that slowly, iteratively get's improved.

**Comment by goldingn** [comment]
Yup, great to have a draft up there though!
