### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#175]
As this is hopefully going to start becoming a bit more of a community, I don't know if we might want to have some sort of code of conduct at some point. For example there's one [here](https://github.com/sckott/scrubr/blob/master/CONDUCT.md).

So far we are a pretty non-diverse bunch. So I think something to make it clear that it's a friendly community would be good.

**Comment by goldingn** [comment]
Completely agree. Should we link to the original? not sure what's changed in the scrubr one

**Comment by timcdlucas** [comment]
Yes original is probably best. Unless there's something stupid in it.
