### ISSUE TITLE
Warning: no function found corresponding to methods exports from 'raster' for: 'overlay'

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#182]
I get this warning when I build. I can find no reference to 'overlay' in the scripts anywhere, that is not surprising since it is presumably the class of an object. @goldingn I'm hoping you know where this is coming from, it only appeared after I pulled your recent changes to the code.

**Comment by goldingn** [comment]
Weird - I don't see this in the travis report and don't get it when I build locally.

`overlay` is a function in raster (used to combine two rasters), but I can't see it in the code either, let alone any exports.

Could be a raster package version issue perhaps?

**Comment by AugustT** [comment]
Currently using raster_2.4-18...

... updated to 2.4-20...

Warning disappears. I will update dependency to >= 2.4.-20

**Comment by goldingn** [comment]
OK cool - weird warning though...
