### ISSUE TITLE
explicit tagging in module docs

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#183]
Many (most?) of the module Roxygen blocks use Roxygen's implicit tagging. E.g. the first line is assumed to be the title.

This is making it a bit difficult for Gef to parse when designing the web front end for the module repo (though he will probably switch to parsing with roxygen), may make it difficult write checks for modules (part of #159) and is likely to be confusing for module developers.

Fixing this is just a matter of going from e.g.:

```
#'BiasBackground: Generate background data using a bias grid
#'
#'This process module genereates a sample of background records according to some spatial model of recording bias,indicated by a raster layer.
#'
#'Module type: Process
```
to
```
#' @title BiasBackground: Generate background data using a bias grid
#'
#' @description This process module genereates a sample of background records according to some spatial model of recording bias,indicated by a raster layer.
#'
#' @details Module type: Process
```

**Comment by AugustT** [comment]
Yeah I think this is a good idea. Also relevant to #158. Is there an easy way to rebuild all the modules or is it just as case of reading them in and manipulating them in R?

**Comment by goldingn** [comment]
Not sure what you mean by rebuilding them - do you mean copy-pasting them into `BuildModule`?

Surely it would be easier just to manually edit them at this point and make sure they pass checks?

**Comment by goldingn** [comment]
I've explicitly tagged all of the modules with this PR: https://github.com/zoonproject/modules/pull/44

We'll want to define a minimum set of tags in module tests too, and improve a lot of the docs but this issue is closed at least
