### ISSUE TITLE
plot.Workflow - Modules not in repo

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#191]
It looks from the code that if a module is not on the repository it is supposed to be coloured differently however this does not seem to work
```r
library(zoon)

directory <- tempdir()

#missing module
  myMissing <- function(.data){
      occurrence <- .data$df
      ras <- .data$ras
      
      noccurrence <- nrow(occurrence)
      
      df <- occurrence
      names(df)[6:ncol(df)] <- names(ras)
      
      return(list(df=df, ras=ras))
    }
  
  BuildModule(object = myMissing,
             type = 'process',
             title = 'missing',
             description = 'test',
             author = 'tom',
             email = 'tom@tom.com',
             dir = directory)
  
  LoadModule(module = file.path(directory, 'myMissing.R'))
  
  work4 <- workflow(occurrence = UKAnophelesPlumbeus, 
                    covariate = UKAir,
                    process = myMissing,
                    model = LogisticRegression,
                    output = PrintMap)

plot(work4)
```
![image](https://cloud.githubusercontent.com/assets/3987564/10397853/b6d28540-6ea1-11e5-9821-5b5707a3eebb.png)

**Comment by AugustT** [comment]
@GregMci might have insight here...

**Comment by GregMci** [comment]
Just setting up ZOON on my new computer and I'll check it out...

**Comment by GregMci** [comment]
It looks like the InModuleList are now set to be true.... https://github.com/zoonproject/zoon/blob/master/R/plot.zoonWorkflow.R#L205 
... even if they are not. Can check with you both in Oxford :)

**Comment by AugustT** [comment]
Thanks for the pointers. I have come across a number of quirks with this but I think I have got to the bottom of all of them. Fixes in a PR, coming to a repo near you soon

**Comment by GregMci** [comment]
Good work! Let me know if it doesn't pan out...
