### ISSUE TITLE
RerunWorkflow with string arguments

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#192]
I can't remember if we decided that the `Bioclim(res = 5)` type syntax was going to be the only allowed syntax.

However, currently, quoted module names do work but they are no then reruneable.

    z <- workflow(occurrence = "UKAnophelesPlumbeus",
                  covariate  = UKAir,
                  process    = OneHundredBackground,
                  model      = RandomForest,
                  output     = PrintMap)
     
    RerunWorkflow(z)

    Error in GetModule(as.character(x$module), forceReproducible) : 
      Cannot find " "UKAnophelesPlumbeus" ". Check that the module is on the zoon repository or in the     global namespace.

**Comment by goldingn** [comment]
Good catch. I'd be inclined to restrict it to non-strings. Simpler to have one interface and probably simpler code just to reject strings.

**Comment by timcdlucas** [comment]
The only case I can think where some sort of string interface might be useful is if you're doing a lot of modules. Like if you're inputting 20 model modules, perhaps it's easier to do a list of modules outside the workflow call. This would be easier as strings than unevaluated objects.

But not sure.

**Comment by goldingn** [comment]
Hmm, wouldn't be too fiddly to convert from a string to an expression.

I'd rather preserve the single interface and provide utility functions to help set up these batch models (essentially pasting and then converting to an expression).

I think a utility function like that would be similar to #176, but with expansion from a vector of arguments

**Comment by AugustT** [comment]
This is now fixed with the changes I made to RerunWorkflow and ChangeWorkflow in f6ba44b11c89618eff46b91037bf3ee81e40af14
