### ISSUE TITLE
undocumented argument in MachineLEarn

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#208]
The [R CMD check results for the modules R package](https://travis-ci.org/zoonproject/modules/jobs/85702466) have no errors, but several warnings and notes.

Most of these aren't relevant because it's not a real package so we wouldn't expect imports, helpfile links etc. to work properly, and there are loads of objects that would be exported from the code but the checks can't see that.

The only one I've spotted that is relevant is this one:

```
Undocumented arguments in documentation object 'MachineLearn'
  ‘metric’
```

**Comment by timcdlucas** [comment]
I've fixed these but am getting 
    Error in unstack(rev(stack(x))) : 
      error in evaluating the argument 'x' in selecting a method for function 'unstack': Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
      Cannot create a RasterLayer object from this file. (file does not exist)

when I `document()` the package. Are we still manually using `document` to build .Rd files or is that CI'd? Basically I have no idea what this error is about.

**Comment by goldingn** [comment]
Weird. Yeah, we're still documenting locally and pushing the docs. Will see if I can replicate.

**Comment by goldingn** [comment]
@timcdlucas could you push your failing branch to github so I can try it on my machine?

**Comment by timcdlucas** [comment]
https://github.com/zoonproject/modules/tree/fixMLPR 

There you go.

**Comment by goldingn** [comment]
works fine for me. Switch it off and on again?

**Comment by goldingn** [comment]
btw you pushed that branch straight to zoonproject, and in the branch you reverted my recent changes (including deleting the travis yaml)

**Comment by goldingn** [comment]
confused Travis slightly: https://travis-ci.org/zoonproject/modules/builds/85711047 :)

**Comment by AugustT** [comment]
This is the issue with Roxygen. I fixed the bug in their dev version so if you install roxygen from github it should work. I think my fix should go into their next CRAN release

**Comment by AugustT** [comment]
stack and unstack are functions in raster and utils. https://github.com/klutometis/roxygen/pull/383

**Comment by goldingn** [comment]
I just pushed back to fixMLPR, bringing it up to date with master

**Comment by goldingn** [comment]
closed in https://github.com/zoonproject/modules/pull/49

**Comment by timcdlucas** [comment]
Yes it works on my machine just restarting R (not reinstalling Roxygen.) 

I did mean to push to zoonproject, but as a seperate branch. Thought that was easier?

But, did you fix my mess ups then? Issue is closed so I'm guessing so.

**Comment by goldingn** [comment]
Yup, that's cool. I was expecting you would push to a separate branch on your fork. Was just a bit flummoxed as you managed to trigger a Travis run without a yaml!

What you did was better anyway, as it meant I could edit, bring up to speed and merge. So all gravy.

**Comment by AugustT** [comment]
Yum, we like gravy!
