### ISSUE TITLE
all modules with non-internal arguments should have default values

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#210]
All module arguments except the internally used ones (e.g. `.df` and `.model`) should have default values so that they can be tested automatically.

i.e. these are wrong:

```r
SpOcc <- function(species,
             extent,  # <- no default
             databases = 'gbif', ...
```
```r
MachineLearn <- function (.df,
            method,  # <- no default
            tuneLength = 8, ...
```

and these are right:

```r
SpOcc <- function(species = 'Ailuropoda melanoleuca',
             extent = c(-180, 180, -90, 90),
             databases = 'gbif', ...
```
```r
MachineLearn <- function (.df,
            method = 'glmnet',
            tuneLength = 8, ...
```

This will be enforced by tests soon, but existing modules (especially occurrence and covariate modules) need editing.

**Comment by AugustT** [comment]
The requirement for defaults should also be enforced in the BuildModule function (or at least give a warning)

**Comment by goldingn** [comment]
Yup, I think it would be fair to error if there aren't default args!

**Comment by AugustT** [comment]
Any ideas for a default for BiasBackground @goldingn ??

```r
#'@param bias Raster with cells giving the relative probability of a background record being sampled there.

BiasBackground <- function (.data, bias, n = 100)
```

Needs to be a raster layer...

**Comment by goldingn** [comment]
Hrmmmm...  How about we delete `BiasBackground`, add a `bias` argument in `Background` with default `bias = NULL`, then internally either do the BiasBackground method or Background method?

Seems a nicer an approach, if you're happy to lose a module.

I'm happy to do this, shall I just PR to the current version of zoonproject/modules or will that break everything?

**Comment by timcdlucas** [comment]
I think the fewer modules the better a lot of the time. So I think this is a good idea.

**Comment by goldingn** [comment]
Cool, btw roxygen2 v5 is now on CRAN. My PR will have an updated version comment at the top of modules docs...

**Comment by goldingn** [comment]
Also - the version number isn't added to docs in v5! Woo!

**Comment by AugustT** [comment]
Nice go for it, you won't break anything.... I don't think!
