### ISSUE TITLE
Can't Build Vignettes

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#213]
I updated all my R packages today and now I can't build vignettes. I think this is a bigger Rstudio/stringi issue. I'm asking around for a fix but in the meantime [I'm going to leave this here](http://stackoverflow.com/questions/33306592/object-c-stri-join-not-found-using-knitr-in-rstudio). Also if you have not updated your packages recently, feel free to rebuild the vignettes!

When using the knit button in Rstudio I get an error `object 'C_stri_join' not found`.

Here is an example:

    ---
    title: "Sample Document"
    output:
       html_document:
       toc: true
       theme: united
    ---
      
    
    
    Here we go
      
    ```{r}
    x <- 1
    
    str(x)
    ```

The error is as follows:

    Error in stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE) : 
      object 'C_stri_join' not found
    Calls: suppressPackageStartupMessages ... evaluate_call -> handle_output -> <Anonymous> -> str_c -> stri_c

This comes after a recent update of my R packages:

    > sessionInfo()
    R version 3.2.2 (2015-08-14)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1
    
    locale:
    [1] LC_COLLATE=English_United Kingdom.1252 
    [2] LC_CTYPE=English_United Kingdom.1252   
    [3] LC_MONETARY=English_United Kingdom.1252
    [4] LC_NUMERIC=C                           
    [5] LC_TIME=English_United Kingdom.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    loaded via a namespace (and not attached):
    [1] htmltools_0.2.6 tools_3.2.2     yaml_2.1.13     rmarkdown_0.8.1
    [5] digest_0.6.8   

The error seems to originate from the call to `str` in the R code chunk since the following works without error:

    ---
    title: "Sample Document"
    output:
      html_document:
        toc: true
        theme: united
    ---
      
    
    
    Here we go
      
    ```{r}
    x <- 1
    
    # str(x)
    ```

This is similar to [this issue][1] but little details are given there.

  [1]: http://stackoverflow.com/questions/32575397/c-stri-join-not-found-for-knitr

**Comment by goldingn** [comment]
I can't replicate on my mac using the latest versions of RStudio (0.99.486), and knitr on CRAN (1.11) or github (1.11.9). The first file works fine with the knit button.

BTW, that's not normally part of my workflow. I normally use:
```r
devtools::document(roclets=c('rd', 'collate', 'namespace', 'vignette'))
```
triggered from CMD-SHIFT-D in RStudio. Perhaps it will work if you run the following at the R prompt?:
```r
devtools::document(roclets='vignette')
```

**Comment by AugustT** [comment]
What version of stringi do you have?

**Comment by AugustT** [comment]
Reinstalling stringi seemed to solve this issue

https://github.com/Rexamine/stringi/issues/198#issuecomment-150777721

**Comment by goldingn** [comment]
I'm on 0.5-5 apparently

**Comment by AugustT** [comment]
I'm on 1.0-1 .... I point the finger of blame

![](http://davidpalethorpe.files.wordpress.com/2012/06/blame-2.jpg)
