### ISSUE TITLE
Claim authorship

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#215]
Hey @goldingn @timcdlucas ,

Many modules are missing authorship. I'm going to add generic 'Zoon Developers' authorship to all modules. If you want to claim one as your own or know someone deserves their name on a module please go ahead and correct it.

I will close this issue in a month,

Tom

**Comment by goldingn** [comment]
I'm happy with Zoon Developers for anything I've touched!

@timcdlucas you should definitely take credit for the caret module!

**Comment by timcdlucas** [comment]
OK I'll take MachineLearn. Probably nothing else. Nearly everything else has been edited somewhere along the line anyway.
