### ISSUE TITLE
Process and Model modules should specify data types

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#216]
Some modules only work with presence/absence or presence-only data. This currently means testing for these modules breaks as we cannot run them through all test work flows.

Do we think this can go in a @section? perhaps `Data type`. I guess this will only be needed for process and model modules. 

This can then be picked up in testing to ensure only appropriate workflows are run.

**Comment by timcdlucas** [comment]
Some models also are type specific (e.g. presence only).

I worry about things that limit the types of data people can use. Are presence/absence, presence-only and abundance the only data types people use? Probability of occurrence as an input as well perhaps?

**Comment by AugustT** [comment]
Add @section tag to all:
- [ ] occurrence modules
- [ ] model modules
- [ ] process modules

- [ ] add requirement to module testing
- [ ] add details to 'building a module' vignette
- [ ] add details to buildmodule function
