### ISSUE TITLE
add preliminary version numbers for existing modules

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#218]
This will be handled properly by the web app in the future, but needed now  for testing

**Comment by goldingn** [comment]
also a submission date

**Comment by AugustT** [comment]
This will be added as `@section version:` at the same time I will add `@section submission date:`

**Comment by AugustT** [comment]
Added as:
```r
#' @section Version: 1.0
#' @section Submission date: 2015-11-13
```
