### ISSUE TITLE
tests are failing in the R-devel tests on Travis

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#220]
https://travis-ci.org/goldingn/zoon/jobs/88168300

I've re-run it a couple of time to no avail.

This is up to date with the main branch which passes: https://travis-ci.org/zoonproject/zoon
which is weird. Maybe this is because my version was checked a few days afterwards?

**Comment by goldingn** [comment]
```
testthat results ================================================================
OK: 243 SKIPPED: 0 FAILED: 6
1. Failure (at testGetModuleList.R#13): GetModuleList renew 
2. Failure (at testGetModuleList.R#14): GetModuleList renew 
3. Failure (at testGetModuleList.R#17): GetModuleList renew 
4. Failure (at testGetModuleList.R#31): GetModuleList no renew 
5. Failure (at testGetModuleList.R#32): GetModuleList no renew 
6. Failure (at testGetModuleList.R#35): GetModuleList no renew 
```
https://travis-ci.org/zoonproject/zoon/jobs/87540056#L4064-L4069

**Comment by goldingn** [comment]
probably worth waiting a bit too see if they fix something in R-devel

**Comment by AugustT** [comment]
Here are the specific errors. Looks like GetModuleList is not returning what it should be.

```
1. Failure (at testGetModuleList.R#13): GetModuleList renew --------------------
"LocalOccurrenceData" %in% modList$occurrence isn't true

2. Failure (at testGetModuleList.R#14): GetModuleList renew --------------------
"LocalRaster" %in% modList$covariate isn't true

3. Failure (at testGetModuleList.R#17): GetModuleList renew --------------------
"PrintMap" %in% modList$output isn't true

4. Failure (at testGetModuleList.R#31): GetModuleList no renew -----------------
"LocalOccurrenceData" %in% modList$occurrence isn't true

5. Failure (at testGetModuleList.R#32): GetModuleList no renew -----------------
"LocalRaster" %in% modList$covariate isn't true

6. Failure (at testGetModuleList.R#35): GetModuleList no renew -----------------
"PrintMap" %in% modList$output isn't true
```

**Comment by AugustT** [comment]
I think this is because R oxygen now seperates 'see also' packages with a ',' not a ';'. Working on a fix

**Comment by AugustT** [comment]
@goldingn can we modify the .yml or something to get Travis to test the package every day to check for errors rather than just when a push is made? My rnbn travis does this. I was a little surprised to see that zoon had not rebuilt for so long and hence we might be late to pick up new bugs.

**Comment by goldingn** [comment]
does your rnbn travis run daily? From here it looks like it runs after every push: https://travis-ci.org/ropensci/rnbn/builds

From this thread, it doesn't look like Travis supports daily builds natively: https://github.com/travis-ci/travis-ci/issues/582

But it can be hacked by scheduling pushes, and there's a third-p[arty web app for that: https://nightli.es/

Shall I sign us up?

**Comment by AugustT** [comment]
It does run daily (well frequently anyway), I have not pushed to it for some time but it ran this morning https://travis-ci.org/ropensci/rnbn it was set up by the ROpenSci crew so perhaps they use a service like the one you suggest?

**Comment by goldingn** [comment]
Aha, right you are. ROpenSci have this heroku app running: https://github.com/ropensci/travis-restarts
Nightlies looks like it'll do the same thing (it was only created this year, The ROpenSci solution was started in 2014 by the looks of it) so I'll sign up for that

**Comment by goldingn** [comment]
well that was easy.

**Comment by AugustT** [comment]
Sweet. Can you post a link here to the app /process for reference?

**Comment by goldingn** [comment]
There's nothing publicly displayed, but you just sign into https://nightli.es/ with your GitHub credentials and flick a switch...

![image](https://cloud.githubusercontent.com/assets/4450731/11147937/7a3598b2-8a11-11e5-80a0-1fc0cd2bc752.png)

**Comment by AugustT** [comment]
Thanks!
