### ISSUE TITLE
Bug in Crossvalidate

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#223]
I think I'm right in thinking this is a mistake in the code but want a second opinion in case I'm about to add a bug. 

Here is some code from crosvalidate:

``` r
  # if presence absence, create folds separately to give well balanced groups
  # if presence only or abundance etc., just split randomly into folds.
  if (all(c(1,2) %in% occurrence$value) & all(occurrence$value %in% c(1,2) )){
    fold <- rep(NA, NROW(occurrence))
    fold[occurrence$value == 1] <- sample(1:k, sum(occurrence$value == 1), replace=TRUE)
    fold[occurrence$value == 0] <- sample(1:k, sum(occurrence$value == 0), replace=TRUE)
  } else {
    fold <- sample(1:k, NROW(occurrence), replace=TRUE)
  }
```

Surely the first line should be...
```
 if (all(c(0,1) %in% occurrence$value) & all(occurrence$value %in% c(0,1) )){
```
...since we are looking for presence absences?

@timcdlucas

**Comment by goldingn** [comment]
Your version looks right to me @AugustT. Will let Tim chime in though as he wrote it.

Do we have a different code for background points and true absence points? If so this should be made to apply for presence-background too.

**Comment by timcdlucas** [comment]
Yes I think you're right. I was probably thinking of factor levels or something.

Also, 
        fold[occurrence$value == 1] <- sample(1:k, sum(occurrence$value == 1), replace=TRUE)

is not a great way to split the data. It will be pretty even for large datasets but with small datasets you could end up with quite uneven sized groups.

    sample(rep(1:k, ceiling(sum(occurrence$value == 1) / k)), sum(occurrence$value == 1))

is better. Think it guarantees only being unbalanced by 1. Can I leave that with you if you're editing and PRing this file anyway?

**Comment by timcdlucas** [comment]
@goldingn It should deal with background points fine. It just checked whether there is both 0 and 1 and only 0 and 1. So that will catch p/a and p/background.

**Comment by goldingn** [comment]
Cool thanks. I was confusing `type` and `value` anyway.

Presumably this would also stratify for counts where only 0s and 1s were observed, but not where0s, 1s and 2s were observed? That's not ideal behaviour, but bot critical at this point anyhow.

**Comment by AugustT** [comment]
@timcdlucas I'll modify and do a PR

**Comment by timcdlucas** [comment]
Yeah it could catch counts (though conceptually... counts that are 0s and 1s are the same as p/a anyway?)

We haven't really defined what terms we're using for counts and abundance. Or whether we're inforcing a strict taxonomy of data types.

Could add a 

    !('abundance' %in% occurrence$type)

Or 

    all(occurrence$type %in% c('presence', 'absense', 'background'))

**Comment by goldingn** [comment]
Not the right place for this, but I think it's interesting so ...

A **1** in a presence-absence model denotes observing *one or more* individuals, whereas in a count model it denotes observing exactly one. So they are different.
You can link the two things nicely in a single model if you model presence-absence data with a complimentary log-log link, and counts with a log-link since the complimentary log-log returns the probability of observing one or more. Then you have:

> *PA*<sub>i</sub> ~ Bernoulli(*p*<sub>i</sub>)
> *C*<sub>i</sub> ~ Poisson(*λ*<sub>i</sub>)
> *p*<sub>i</sub> = 1 - exp(-*λ*<sub>i</sub>)
> *λ*<sub>i</sub> = exp(*μ*<sub>i</sub>)

(where *PA* are presence-absence data, *C* are counts, and *μ* is your underlying model)

If you model presence-only data as a point process, then they become counts (of a sort) and you can link all the data types into a single model. Which is fun.

**Comment by timcdlucas** [comment]
I agree they are not the same in general. 
Just trying to work through the case where you have counts with only 1 or 0. In which case you have a small *λ* (and therefore many more 0s than 1s). 

If you have fairly even 0s and 1s then the data doesn't fit a poisson well (you'd expect some 2s etc.) so then gets a bit funky. 

Anyway, pretty niche case.

**Comment by timcdlucas** [comment]
Did the actual original issue here get fixed and PRed? If so I'll close this.

**Comment by AugustT** [comment]
Thanks for the nudge. I have not fixed this yet, will do
