### ISSUE TITLE
'Appify' output module

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#224]
### Turn workflow into deployable web-app

I think this is totally doable using shiny.

Firstly display each of the module outputs in their own tabs using searchable tables and interactive maps. Secondly allow the user to change parameters on the fly (runs ChangeWorkflow in the back end). Could be a really nice way to visualise and play with a workflow. The user would then be able to pick up the shiny app and deploy it to the web if they fancy.

_EDIT: I suggested allowing people to change parameters and re-run workflows. I now think this is a bad idea as it is a move towards a GUI for zoon which I don't think we want to do. Instead the app should make the workflow downloadable and encourage people the re-work it in R_

**Comment by goldingn** [comment]
Cooooooool. Sounds great!

**Comment by AugustT** [comment]
FYI - I'm super excited about this module!

**Comment by AugustT** [comment]
Hi @goldingn @timcdlucas @GregMci I have a first iteration of this module that I would like to get your feedback on.

First you will need these packages installed (they are all used elsewhere in zoon so you should have them -  except shiny)
```r
  zoon::GetPackage('shiny')
  zoon::GetPackage('DT')
  zoon::GetPackage('leaflet')
  zoon:::GetPackage('htmlwidgets')
  zoon:::GetPackage('viridis')
  zoon:::GetPackage('rgdal')
```

Once you have all these installed you can launch a demo from my repo. This is what will pop-up when people run a workflow with `Appify` as an ouput module

```r
shiny::runGitHub('augustt/appify')
```

Have a look around and let me know what you think. I will add a splash page with a little overview of zoon so you won't land on the occurrence page. The splash page will also have information about how the user can share the shiny app that `Appify` has created for them. 

![image](https://cloud.githubusercontent.com/assets/3987564/14893354/f1c8242a-0d66-11e6-9b71-458788c44dc1.png)

**Comment by timcdlucas** [comment]
This is outstanding work.

I didn't have DT installed. Just something that might need to be in a `RequirePackages` call or something.

I don't know if it's easy but I feel a better default view for the occurrence data table would be a 10-20 row scrollable view.

I think either the call or a schematic of the workflow would be a really useful thing to land on. Know what has been listed makes navigation much easier. I was expecting an unlisted workflow first, so took me a while to see the tabs to select 1 UKAnophelesPlumbeus 2 UKAnophelesPlumbeus.

And is it currently built so that all output modules will be printed in separate tabs? That would be so great.

Will have another go later. But to be honest it's so good already I don't have much more to input.

**Comment by timcdlucas** [comment]
btw, this is the first time that I noticed how bad the UKBioclim + Anopheles plumbeus model is. Because the presences are biased to UK only, it predicts lower occurrence probability moving south into France.

Might be a good teaching example actually.

**Comment by goldingn** [comment]
This looks amazing! I'm away from my computer for a bit but super excited to try it out!

**Comment by AugustT** [comment]
@timcdlucas Thanks for the comments.

I spent a lot of time think whether this should be a module or an additional zoon function. I went for a module. As a result this does not have access to the ouput modules 'results' and it is more difficult to plot the workflow (would be easy if I had the whole workflow using plot.zoonworkflow).

Your suggestions make me think that you expected Appify to be operating on the entire workflow, so now I'm thinking that perhaps this should be it's own function in zoon which can be executed on a workflow object. This would allow me to improve the occurrence tab (actually what you see here is the occurrence data post-process module), include anything returned by output modules in the output window and more easily create the splash page. Let me know if you agree @goldingn

**Comment by timcdlucas** [comment]
Ah ok. Well I think it's pretty great as is.

And as a module, I guess the app is an output and wouldn't be expected to standalone. So I think this is reasonable.

**Comment by goldingn** [comment]
I'm a bit torn.

It would be great to have the features you describe, but I also really like the idea that other people can build on this easily.

Would it be worthwhile passing more information to output modules instead?

We could make a workflow pass itself as an argument to the output modules. Though a) we'd have to be a bit careful about duplicating objects etc. and b) that might be sufficiently baffling that it raises the technical barrier to module writing.

Another thing to consider would be a 6th type of modules to summarise complete workflows in a particular way. E.g. writing reports in different formats 

I'm not advocating for any of these approaches, but it's something we should think hard about.

**Comment by GregMci** [comment]
I'll have a proper look asap, but from the first mail this looks great. Good work Tom!
 
Date: Fri, 29 Apr 2016 02:22:55 -0700

**Comment by AugustT** [comment]
@goldingn I agree that the fact I am limited here means we should think about how we can change the structure to lift those limitations on output modules, which of all the modules types, are the most dificult for us to predict usage.

I'm not sure I like the idea of the 6th module type as it falls outside the nice framework we have.

I'm also not keen on a workflow passing itself to the output module, its a bit 'inception' and confusing

![inception](https://media.giphy.com/media/kOIbusN7fPnkk/giphy.gif)

I do like the idea of passing more into the output modules, this will give more flexibility to people who are writing output modules

**Comment by GregMci** [comment]
I agree that (in my far less technical view) the 6th module falls outside the ZOON framework. An all-in-one ‘sixth module’ appify does sound like it should be an add-in app or a ZOON function like plot.zoonworkflow. 
+1 for “flexibility to people who are writing output modules”

**Comment by AugustT** [comment]
I did some work on the landing page, took a long while to figure out how to do a flowchart, I got something at the end.

![image](https://cloud.githubusercontent.com/assets/3987564/14922603/6edf5374-0e30-11e6-91cd-a4721bf02205.png)

**Comment by timcdlucas** [comment]
Looks good! Having number 1 and 2 is good.

**Comment by AugustT** [comment]
This module is on its way to the repository so that we can use it. I did hit a few issues when trying to turn my code into a module. The major one was that I have overlooked the fact that output modules are applied to each model output in turn, my code was set up to handle lists of modules putting them in tabs etc. As a result none of this functionality is ever used, never mind.
