### ISSUE TITLE
Accessor functions.

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#229]
Rereading about the confusing with accessing the nested list made me think that perhaps accessor functions would be useful.
e.g. the accessor functions for lm objects.

    x <- lm(rnorm(10) ~ c(1:10))
    x$coef
    coef(x)

So we might have something like:

    work1 <- workflow(occurrence = UKAnophelesPlumbeus,
                      covariate  = UKAir,
                      process    = OneHundredBackground,
                      model      = LogisticRegression,
                      output     = PrintMap)
    
    occurrence(work1)
    process(work1)

Once lists and chains come in, the results would still be a list, but perhaps removing that one layer of lists would help.

**Comment by AugustT** [comment]
It would definitely be easy to do.

**Comment by timcdlucas** [comment]
Yeah, completely trivial... so I'll do it some point if it's useful. If it just... makes the manual longer for no good reason, I won't.

**Comment by AugustT** [comment]
Does it make the package easier to use? Yes. Is it trivial to implement? Yes. 

Gets a +1 from me.

What do you think `output(work1)` would look like?

**Comment by timcdlucas** [comment]
In this specific case? 

    output(work1)
    
    [[1]]
    NULL
    
It's just not a useful output module to be accessing. 

But this does make sense.


    work2 <- workflow(occurrence = UKAnophelesPlumbeus,
                      covariate  = UKAir,
                      process    = BackgroundAndCrossvalid,
                      model      = LogisticRegression,
                      output     = PerformanceMeasures)
    
    
    output(work2)
    
    [[1]]
    [[1]]$auc
    [1] 0.6657145
    
    [[1]]$kappa
    [1] 0.424773
    
    [[1]]$omissions
    [1] 0
    
    [[1]]$sensitivity
    [1] 1
    
    [[1]]$specificity
    [1] 0.345679
    
    [[1]]$proportionCorrect
    [1] 0.802974
    

Perhaps if the modules aren't chained/listed it should ignore the additional list level as well.

    output(work2)

    $auc
    [1] 0.6657145
    
    $kappa
    [1] 0.424773
    
    $omissions
    [1] 0
    
    $sensitivity
    [1] 1
    
    $specificity
    [1] 0.345679
    
    $proportionCorrect
    [1] 0.802974

**Comment by AugustT** [comment]
Agree. if the list length is 1 drop the top level.
