### ISSUE TITLE
Vignettes install packages = CRAN sad-face

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#233]
A recent message from CRAN folks

*"Finally, I see that re-building the vignettes apparently installs several packages: this is not the way to do things.  You should put these packages into your \VignetteDepends and package DESCRIPTION Suggests entries instead."*

**Comment by goldingn** [comment]
>this is not the way to do things

Pffft.

We don't lose a huge amount by putting them in VignetteDepends & suggests I guess (except our precious time).
