### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#24]
The way the workflow is currently written, you get multiple copies of the wholw environmental rasters. I think this is probably a bad idea but would need to think about how best to fix it.

**Comment by goldingn** [comment]
Is this definitely the case? I would have thought R wouldn't actually copy these in memory until the very last minute (normally converting into something else).

Worth profiling memory and cpu usage further down the line to check this all out

**Comment by timcdlucas** [comment]
Ok yeah, R handles this all very well. Even two separate workflows using the same raster will share the memory location.


    > library(pryr)
    
    > work1 <- workflow(occurrence = UKAnophelesPlumbeus,
    >                   covariate  = Bioclim,
    >                   process    = OneHundredBackground, 
    >                   model      = LogisticRegression,
    >                   output     = SurfaceMap)
    
    > object_size(work1[[2]][[1]])
    117 kB
    
    > object_size(work1[[3]][[1]]$ras)
    117 kB
    
    > object_size(work1[[2]][[1]], work1[[3]][[1]]$ras)
    117 kB
    
    
    > work2 <- workflow(occurrence = UKAnophelesPlumbeus,
    >                   covariate  = Bioclim,
    >                   process    = list(OneHundredBackground, OneHundredBackground, OneHundredBackground),
    >                   model      = LogisticRegression,
    >                   output     = SurfaceMap)
    
    
    > object_size(work2)
    1.27 MB
    
    > object_size(work2[[3]][[1]]$ras, work2[[3]][[2]]$ras)
    117 kB
    
    > object_size(work1, work2)
    1.86 MB
