### ISSUE TITLE
replicate for simulated data

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#242]
Been reading papers that we might reproduce in the applications pair and realise we haven't thought about how to usefully including repeated simulations in a workflow.

For example, running an analysis on 100 simulated datasets would currently be a 100 long list `occurrence = list(simdata, simdata, simdata, ...)`

I don't think it's easy to have a module that splits the workflow.

The easiest solution might be another function in the vein of `Chain` and `list`. Perhaps `Replicate`.

So the above occurrence Sims would become `occurrence = Replicate(simdata, n=500)`

**Comment by AugustT** [comment]
I'm implementing this now. We now need a simdata occurrence module that can be used with this functionality

**Comment by timcdlucas** [comment]
Excellent! I have no time at the moment to work on anything zoon related I'm afraid. So glad you're doing this!

Guess it might be worth making a very general simdata module that takes a function or something. Unless there's a completely dominant way of simulating data in the lit which I'm not sure there is.
