### ISSUE TITLE
PrintMap output doesn't scale correctly

### ISSUE THREAD

**Issue by RTbecard** [zoonproject/zoon#245]
When running the following code from the `Building modules` vignette:
```r
workl1 <- workflow(occurrence = Lorem_ipsum_UK,
                   covariate = UKBioclim,
                   process = OneHundredBackground,
                   model = LogisticRegression,
                   output = PrintMap)
```

The points layer rescales independently of the underlying raster layer when the output panel is resized after the function has run.

1. Initial output after running the workflow.
![1](https://cloud.githubusercontent.com/assets/6226719/13819582/4806eb58-eb9a-11e5-89c3-58c248c9f18c.png)

2. After rescaling my ouput panel, the points are in different positions relative to the map.  You can see the points are not following the axis scaling here.
![2](https://cloud.githubusercontent.com/assets/6226719/13819583/48092a6c-eb9a-11e5-8d77-231076fb210d.png)

**Comment by AugustT** [comment]
What odd behaviour! I'll have a dig and see what I can find

**Comment by RTbecard** [comment]
I'm running on Ubuntu 14.04 in case its relevant!

**Comment by RTbecard** [comment]
I'm running on Ubuntu 14.04 in case its relevant!

**Comment by timcdlucas** [comment]
This has been annoying me for a while! Just to point out, if you rescale the window and then replot, the alignment works fine. And pngs etc. should also be fine.

It's a problem with how raster and plot interact and is not easily fixed.

http://stackoverflow.com/questions/5977419/ploting-artefact-with-points-over-raster/5985523#5985523

The solution here requires using an internal raster function, which is not recommended. 

Or this question:
http://stackoverflow.com/questions/28371270/resizing-plot-output-causes-raster-and-points-to-become-misaligned

The suggested solution here is to use the rasterViz package. I guess we would have to decide whether we would want to add an extra dependency or create a separate rasterViz module.

**Comment by RTbecard** [comment]
Is using `sp::spplot` an alternative?  `dismo` is dependant on `sp` I think, so zoon already meets the dependancies for this.  You can get the output to look identical to plot I think.

**Comment by RTbecard** [comment]
PS.  Just tested some raster data with overlayed points in `spplot` and the scaling issue doesn't affect it.

**Comment by goldingn** [comment]
@RTbecard what's your code using spplot? Are you plotting the raster or the point (or both) using that?

**Comment by RTbecard** [comment]
You can plot both the raster and spatialpoints in a single call to `spplot`.

Here's a really quick example from generated random data:
```r
require(raster)
require(sp)
require(RColorBrewer)

## Create random raster
rast <- raster(nrows = 500, ncols = 500,xmn = -10,xmx = 10,ymn = -10,ymx = 10,crs = '+NA')
values(rast) <- rpois(500*500,2)

## Create points to plot
points <- SpatialPoints(coords = data.frame(x = c(-9,9),y = c(-9,9)))

## Make points layer
sl <- list('sp.points', points, pch=16, cex=2, col='blue')

## make color scale for raster (Not necessary to use RColorBrewer for this)
cols <- colorRampPalette(c('#000000','#FF0000','#FFFF00'))(256)

## Plot raster with points overlayed
spplot(rast,sp.layout=list(sl),col.regions=cols,cuts=length(cols)-1)
```

**Comment by goldingn** [comment]
OK great, that's a good solution!

In fact the `spplot` method you're using is defined in `raster` so the call to `sp` isn't necessary, which means no additional dependencies!

Should be fairly easy to implement, even though `spplot` has a fairly horrible design.

**Comment by AugustT** [comment]
@RTbecard are you going to implement this in a PR or shall I make these changes?

**Comment by RTbecard** [comment]
I can PR it this evening, but if you want it sooner, feel free to go for it!

**Comment by AugustT** [comment]
No rush, I'll let you have the glory on this one!

**Comment by timcdlucas** [comment]
As this sounds like a fairly fundemental rewrite, don't forget to add yourself to the modules author list defined at the top. If you want to be noted as an author that is.

Also just if this module uses `sp` I think it'll have to go in suggests in the zoon `DESCRIPTION` as it's used in various tests and vignettes. Feel free to leave that to us to add @RTbecard

**Comment by AugustT** [comment]
Yes add yourself as an author. See comment from Nick above which suggests a dependency on `sp` is not needed.

**Comment by timcdlucas** [comment]
Oh yeah. I remember reading that before...
