### ISSUE TITLE
How do module help files get built?

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#254]
I should probably know this... but are module man files supposed to be automatically built? Or am I supposed to do `document()` on the modules package and push the .md files as well?

**Comment by AugustT** [comment]
Roxygen should be used to build the help docs and then push the .Rd, there are no .md files on the module repo.

**Comment by timcdlucas** [comment]
ah yes i meant .rd not .md

I'll build the docs and PR
