### ISSUE TITLE
Builds erroring

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#255]
For release & dev, CRAN & not CRAN.
Apparently this is due to curl & testthat not being available.

This may be a recent change to Rbuilder and may just go away.

**Comment by goldingn** [comment]
Also failing on the modules repo

**Comment by goldingn** [comment]
Looks like the issue is the RStudio CRAN mirror periodically flaking out and becoming inaccessible for installing R packages (see e.g. https://twitter.com/ramnath_vaidya/status/703347489806483456)

The RStudio mirror cran.rstudio.com (for which I think cloud.r-project.org is a synonym, it isn't working either) *should* redirect to the nearest physical mirror  so is a sensible option most of the time. In PR #256 I'm setting it to a physical mirror (Berkeley, guessing the machines Travis uses might be in or near Silicon valley).

Hopefully that'll work.

**Comment by AugustT** [comment]
r-builder has been fixed so they now build

**Comment by goldingn** [comment]
Well done Tom!
