### ISSUE TITLE
Listed Covariates cause problems in output

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#263]
I don't know how we have not come across this before

I get an error from this:

```r
> work2 <- workflow(occurrence = UKAnophelesPlumbeus,
+                   covariate  = list(UKBioclim, UKAir),
+                   process    = OneHundredBackground,
+                   model      = RandomForest,
+                   output     = InteractiveMap)
Loading required package: leaflet
Loading required package: htmlwidgets
Loading required package: viridis
Loading required package: rgdal
rgdal: version: 1.1-3, (SVN revision 594)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.0.1, released 2015/09/15
 Path to GDAL shared files: C:/Users/tomaug/Documents/R/win-library/3.2/rgdal/gdal
 GDAL does not use iconv for recoding strings.
 Loaded PROJ.4 runtime: Rel. 4.9.1, 04 March 2015, [PJ_VERSION: 491]
 Path to PROJ.4 shared files: C:/Users/tomaug/Documents/R/win-library/3.2/rgdal/proj
 Linking to sp version: 1.2-2 
Caught errors:
Error in eval(expr, envir, enclos): object 'layer' not found


 Show Traceback
 
 Rerun with Debug
 Error: Stopping workflow due to error in output module.
 Workflow progress will be returned. 
```

and the same if I use PrintMap. How has this not been seen before. Can someone confirm they get this error too? It seems to originate [here](https://github.com/zoonproject/zoon/blob/master/R/DoModuleFunctions.R#L26) where the output module considers a list coming out of the model module it applies across the model output but only ever uses the first raster.

**Comment by timcdlucas** [comment]
Can confirm the erroor.

https://github.com/zoonproject/zoon/blame/master/R/DoModuleFunctions.R#L26

The reason it hasn't been caught before is because it's part of the changes I made in PR #252.

 I'll try and fix it asap.

**Comment by timcdlucas** [comment]
Actually, looking at the [diff](https://github.com/zoonproject/zoon/commit/17f03a64f76c77596ca8bf562ba1e9d8cb2f09a0) I think it might have been a problem before. 

It might take a little bit of time to get it fixed. It doesn't look that simple.

**Comment by AugustT** [comment]
Ah, that makes sense.I thought it was strange we had not seen it before. I'm also looking for a fix...

**Comment by timcdlucas** [comment]
Just to think out loud a bit:

I think bits like this

```
      output.output <- lapply(model.output, 
                         function(x) do.call(outputName[[1]]$func, 
                         c(list(.model = x,
                                .ras = process.output[[1]]$ras),
                           outputName[[1]]$paras), envir = e))
```

are going to have to change to `lapply`ing over `1:length(model.output)` and those indices going into `process.output[[x]]` type thing.

Might not get to look at this much today.

**Comment by AugustT** [comment]
@timcdlucas can you review this suggestion? I suggest we need one additional if statement within the else that is causing problems. The current issue is that this statement assumes multiple model outputs and one process output. Therefore we can add an if to test if actually they have the same number. We can then build a paired list of the outputs and run a similar apply. This seems to have fixed the issue for me but would like a second opinion

```r

if (length(process.output) == length(model.output)){
       
        # Create a paired list of model and process output
        MP.output <- list()
        
        for(i in seq_along(1:length(process.output))){
          MP.output[[i]] <- list(model.output[[i]], process.output[[i]])
        }
        
        output.output <- lapply(MP.output,
                                function(x) do.call(outputName[[1]]$func, 
                                                    c(list(.model = x[[1]],
                                                           .ras = x[[2]]$ras),
                                                      outputName[[1]]$paras), envir = e))
        
        
      } else { # there must be only one process output and multiple models
       
        output.output <- lapply(model.output,
                                function(x) do.call(outputName[[1]]$func, 
                                                    c(list(.model = x,
                                                           .ras = process.output[[1]]$ras),
                                                      outputName[[1]]$paras), envir = e))
         
      }

```

**Comment by timcdlucas** [comment]
Hi,

Looks good. I think the logic makes sense. I'm still struggling with all this. There's so many combinations.

I don't think you need `seq_along()`. `1:length(process.output)` on it's own does the same thing?

However, I think we need need to deal with the same problem in the chain bit of this function.

```
work2 <- workflow(occurrence = UKAnophelesPlumbeus,
                   covariate  = list(UKBioclim, UKAir),
                   process    = OneHundredBackground,
                   model      = LogisticRegression,
                   output     = Chain(PrintMap, PrintMap))
``` 
This fails with the same error as the problems before. I'll have a look now and see if I can work it out (my brain isn't working today).

**Comment by timcdlucas** [comment]
Also, where are the full workflow tests? Although it'd make them take even longer I think it might be worth building every possible combination of list and chain. Maybe something to only run on big updates or something. 

I make it about 40 workflows...

If we call N - nothing, C - chain, L - list.
And no chains in Models. I can't remember if we banned lists on output as they are just the same as chain.

No lists:
NNNNN
CNNNN, NCNNN, NNCNN, NNNNC, CCNNN, CNCNN, CNNNC, NCCNN, NCNNC, NNCNC,
CCCNN, CCNNC, NCCNC, CCCNC.

Then all those again with Model listed.

List Occurrence:
LNNNN, LCNNN, LNCNN, LNNNC, LCCNN, LCNNC, LNCNC, LCCNC

List covariate:
NLNNN
CLNNN,  NLCNN, NLNNC,  CLCNN, CLNNC,   NLCNC, CLCNN,   CLCNC.

List process:
NNLNN
CNLNN, NCLNN, NNLNN, NNLNC, CCLNN,  CNLNC, NCLNC, CCLNC.

Which isn't totally rediculous. 56.

**Comment by AugustT** [comment]
See testWholeWorkflows.R for the current state of testing. 56 is quite a lot when you have to write all the tests for the various outputs!

**Comment by AugustT** [comment]
writing the tests for #262 I'm going to be hitting a lot of these

**Comment by timcdlucas** [comment]
I might sit down and write the tests at some point. I just worry because I can't hold it all in my head.

I guess it's easiest to do a mega block of tests in a `if(runBigTests){ }` block or something, then we can turn it on when we want.

**Comment by AugustT** [comment]
I'm glad I'm not the only one! I have to get into a groove and do a lot in one day because by the next day I have forgotten what goes where

**Comment by timcdlucas** [comment]
Right,

Think I've fixed both cases using your code and then basically same code applied to the chain output case. 

I'll PR and hope you don't mind that you won't be credited with the commit.

I've added comments clarifying the logic. Which I guess we should do for all the DoModule functions as they are all confusing.

**Comment by AugustT** [comment]
Great stuff.

I've been working on the DoModules scripts all day trying to implement #262 so have been added some comments and re-factoring a little

**Comment by timcdlucas** [comment]
OK, you happy for me to PR and you to pull and deal with merge conflicts?

**Comment by AugustT** [comment]
Nothing I love more than dealing with merge conflict ;)

Go for it

**Comment by timcdlucas** [comment]
@AugustT Just tagging to make sure you see this.
I still don't quite understand travis.

The badge and [this](https://travis-ci.org/zoonproject/zoon/jobs/122844060) says it failed. The PR #265 says it passed?

**Comment by goldingn** [comment]
From what I could see it errored rather than failed. One of the builds couldn't curl something. Probably intermittent so I've re-run

**Comment by timcdlucas** [comment]
Great. Do you own the travis account? Or can I trigger reruns as well?

**Comment by goldingn** [comment]
As a member of the zoonproject organisation you can trigger re-runs. Just log in to travis with your github credentials and there's a button that looks like this: 
        ![screen shot 2016-04-14 at 10 01 34 am](https://cloud.githubusercontent.com/assets/4450731/14513047/f6c1a4dc-0227-11e6-8b34-02e390a208e4.png)

**Comment by goldingn** [comment]
Build now passing on the master branch

**Comment by timcdlucas** [comment]
Excellent cheers!
