### ISSUE TITLE
GBM module incorrect error message???

### ISSUE THREAD

**Issue by cvisintin** [zoonproject/zoon#266]
The GBM module throws this error when using 'presence/background' data:

_Caught errors:
Error in GBM(.df = structure(list(longitude = c(143.6, 146.9, 147.4, 144, : only for presence/absence or presence/background data_

The check is valid, however, the syntax seems to be incorrect; current GBM.R module reads:

    `if (!all(.df$type %in% c('presence', 'absence', 'background'))) {
      stop ('only for presence/absence or presence/background data')
    }`

Should it read:

    `if (!all(.df$type %in% c('presence/absence', 'presence/background'))) {
      stop ('only for presence/absence or presence/background data')
    }`

???

**Comment by AugustT** [comment]
Thanks @cvisintin 

The $type column should be one of `'presence', 'absence', 'background', 'abundance', 'proportion'`. This is outlined [here]('presence', 'absence', 'background', 'abundance', 'proportion'), but should be stated more clearly somewhere. Clearly an observation (a row in your dataset) can be presence or background not both

**Comment by cvisintin** [comment]
Ah yes, I see now, that makes more logical sense.  Thanks.  The link above is broken; perhaps a more clear description in the module tutorial would be useful.

**Comment by AugustT** [comment]
Sorry here is the link, it is at the end of the build a module vignette. I think this should be explained in more detail in the `LocalOccurrenceData` module, is that what you meant? https://github.com/zoonproject/zoon/blob/master/vignettes/Building_a_module.Rmd#occurrence

**Comment by cvisintin** [comment]
Yes, that is what I meant...thanks for following up.  And sorry for not posting the query in the module section :)

**Comment by timcdlucas** [comment]
We actually prefer you to post here. Keeping all the issues in one place is easier.

I won't if we can direct the module issues here in fact.
