### ISSUE TITLE
Instability in Bioclim - remove web calls from vignettes

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#273]
The `Biolclim` package relies on the servers at http://biogeo.ucdavis.edu/ These are not always reliable and experience occasional downtime which can cause builds to fail. I suggest we remove this module from the vignette. In fact it is probably wise to remove all modules that call web services from the vignettes to ensure that similar problems do not occur in the future.

Error appear similar to this:

```
trying URL 'http://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_10m_bil.zip'
Warning in utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  InternetOpenUrl failed: 'The operation timed out'
Quitting from lines 379-390 (Building_a_module.Rmd) 
```

**Comment by timcdlucas** [comment]
Yes probably sensible especially as they make building the vignette slow.

I did deliberately put some tests that use web call modules in the tests. https://github.com/zoonproject/zoon/blob/master/tests/testthat/testWholeWorkflows.R#L64

That was when I first started writing those modules. Now that the basic idea of getting data from the web is very established, they could perhaps be removed to speed things up too.

Currently UKAir is the only raster data built into the package? We might want to add some other data to the package for running tests. UKAir is like... 6 x 8 pixels and only 1 layer. I'm sure two layer tests might catch some errors that don't occur in 1 layer data (and vice versa).

**Comment by AugustT** [comment]
I think we actually want to keep these examples in the vignette as they are quite nice. Instead I'm going to move to pre-building the vignettes before sending them to CRAN. It appears this is fairly common practise but requires us to remember the re-build the vignettes periodically to ensure no issues exist in them (they should be caught in tests anyway)

**Comment by AugustT** [comment]
This has taken a while to sort out as I hit many issues trying to workout how to get the vignettes to build correctly and still find the figures, anyway I think it is sorted now, here are a few notes.

The original .Rmd files are in the vignette_prebuild folder and these are the files you should edit when changing or updating the vignettes. These are then built into md files (r chunks are run) and plots, both are saved to the working directory. These then both need to be moved to the vignettes folder and the md file needs to be renamed as a .rmd file. This rmd file is then built into the html file which is moved to the inst/doc folder. 

Seeing as this is quite complicated I wrote a script to automate the process, it is saved in the vignettes_prebuild folder.
