### ISSUE TITLE
CRAN dislike ':::'

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#284]
Just to keep everyone in the loop I'm having issues trying to get the most recent version of zoon on CRAN because of my use of ':::'. It is used to as roxygen2:::parse_file in buildModule to check modules. I'm chatting with the guys at CRAN and Hadley to try and come to a solution.

**Comment by goldingn** [comment]
Cool, was just considering whether we could copy-paste into zoon (with proper attribution) but roxygen2 is GPL, so incompatible with our MIT licence. Arses.

**Comment by goldingn** [comment]
*arses used as a general expression of annoyance. I'm not calling anyone an arse

**Comment by AugustT** [comment]
Ah.... that is what I was planning on doing...

**Comment by goldingn** [comment]
I think that's right anyway. GPL is copyleft/viral so can only be used with noncommercial licences.

We could always write our own with similar functionality, but Id really rather not.

Are there exported functions we could adapt our code to (e.g. write our bits to disc, then run one of the higher level functions)? We'd take a hit in speed and clarity, but maybe not a critical one.

**Comment by AugustT** [comment]
i'll look into it

**Comment by AugustT** [comment]
None of these options are really feasible. Why do we not have an open license? ... hmm ...

**Comment by goldingn** [comment]
We do! The problem is our MIT is more open than Roxygen's GPL (for some definition of open).

**Comment by goldingn** [comment]
I think I have the bulk of a solution.
`roxygen2` exports the function `roc_proc_text` which they use for testing snippets of roxygen code. That allows us to do:

```r
lines <- readLines(file, -1)
roc <- roxygen2::rd_roclet()
rd <- roxygen2::roc_proc_text(roc, lines)[[1]]
res <- lapply(names(rd),
              function(field, x) x[[1]][[field]]$values,
              rd)
```

running on the file `spThin.R` outputted by the paper, I get something that looks like:

```r
res
```
```
$author
[1] "ZOON Developers, \\email{zoonproject@gmail.com}"

$alias
[1] "spThin"

$description
[1] "Apply the stochastic spatial thinning algorithm implemented in the spThin package to presence data in a presence-background dataset"

...
```

I haven't looked in detail at how this differs from what we currently have, and some of the `section` bits may need reformatting, but it gets us most of the way there.

**Comment by AugustT** [comment]
Aha, I thought you were saying we couldn't use the code because we didn't have an open license, in fact it is because we need to use the same license as them.

Well done for finding that solution! I'll have a look at the details today

**Comment by AugustT** [comment]
I did some modifications to your function and looks like we have a winner

```r
ZoonModuleParse <- function(modulePath){
  
  # Read in the file
  lines <- readLines(modulePath, -1)
  
  # Get the tags out
  roc <- roxygen2::rd_roclet()
  rd <- roxygen2::roc_proc_text(roc, lines)[[1]]
  res <- lapply(names(rd),
                function(field, x) x[[1]][[field]]$values,
                rd)
  
  # flatten 'sections'
  if('section' %in% names(res)){
    
    sections <- lapply(res$section,
                       function(x) paste0(x$name, ':', x$content))
    
    # name sections
    names(sections) <- rep('section', length(sections))
    
    # replace old section with new sections
    res[['section']] <- NULL
    res <- append(res, sections)
    
  }
  
  #format params
  if('param' %in% names (res)){
    
    params <- lapply(names(res$param),
                     function(field, x) list(name = field,
                                             description = as.character(x[field])),
                     res$param)
    
    names(params) <-  rep('param', length(params))
    res[['param']] <- NULL
    res <- append(params, res)
    
  }
  
  return(res)
  
}

# TEST ACROSS ALL MODULES
for(modulePath in list.files('../zoon_modules/R',
                             pattern = '.R$',
                             full.names = TRUE)){
  
  if(basename(modulePath) != 'ModulesDocumentation.R'){
  
    cat(basename(modulePath), '\n')
  
    zoon_parse <- ZoonModuleParse(modulePath)
    roxy_parse <- roxygen2:::parse_file(modulePath, environment())[[1]]
  
    for(name in names(roxy_parse)){
      
      x <- all.equal(roxy_parse[[name]], zoon_parse[[name]])
      
      if(x != TRUE){
        cat(name, '\n')
        print(x)
        cat('\n')
      }
    }
  }
}
```

I'll implement this now

**Comment by AugustT** [comment]
I think this should fix the CRAN issues. However, I suggest we hold of our submission to CRAN until the end of next week so that we can get extra features added in. FYI I might be on a course the entire of the week before the zoon workshop and working the weekend before the workshop too so will try to keep making progress next week.

**Comment by goldingn** [comment]
Nice one! Yep, agree with holding off
