### ISSUE TITLE
Flexible naming of columns in occurrence data

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#288]
This relates to #272 #285 #286 

We need a way to allow flexibility in the columns provided in the occurrence data and at the same time allow us to easily identify the covariate columns. I originally thought I could give covariate columns a prefix but if you do this they no longer match the column names given in the raster which makes predicting fail. 

An alternative is to give the data.frame that comes out of `ExtractAndComb` an attribute with the names of the covariate columns. This retains the matching names but allows us to subset these columns consistently:

```r
df <- Process(work1)$df
df[colnames(df) %in% attr(df, 'covCols')]
```

This will need explaining in the how to build a module vignette so that module makers know that this is the convention. 

If we think this is a bit much I could create a simple function to replace the one liner above 

```r
df <- Process(work1)$df
getCovariates(df)
```

I'm going to start implementing this so shout if you object!

**Comment by timcdlucas** [comment]
I guess the alternative is to split the occurrence data into two data frames. But that's much more hassle.

**Comment by goldingn** [comment]
Excellent solution!

**Comment by AugustT** [comment]
https://github.com/zoonproject/modules/pull/87
