### ISSUE TITLE
option to point zoon to a different repo/branch

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#290]
Currently `zoon` is hardwired to grab modules from [github.com/zoonproject/modules](), because of this line of code in `zoon:::GetModule()`:

```r
    zoonURL <- paste0("https://raw.githubusercontent.com/zoonproject/modules/master/R/", 
        module, ".R")
```
That's what we want the vast majority of users to do, but for development it may be preferable to try out workflows pointing to a different repo (one of our forks) and/or branch (to evaluate a PR). This may also be useful for the workshop if Gef is worried about borking the zoon repo with the website upload system.

---

I think the simplest approach would be to add the following to the `zoon:::.onLoad()` definition in `zzz.R` to set the default repo invisibly:
```r
  if (is.null(getOption('zoonRepo'))) {
    options(zoonRepo = "https://raw.githubusercontent.com/zoonproject/modules/master/R/")
  }
```

and then change the above line in `zoon:::GetModule()` to:
```r
    zoonURL <- paste0(options('zoonRepo'), module, ".R")
```

We'd also need to paste that line into `zoon:::LoadModule()`, in place of the current:
```r
zoonURL <- sprintf('https://raw.githubusercontent.com/zoonproject/modules/%s/R/%s.R',
	            .sha, module)
```

Anyone can then point to a different repo by changing that option, either before or after loading `zoon`.
This is obviously super easy to implement, but I wanted to check I'm not missing something else that  would need to change.

---

This approach would override the deprecated method of tying a `zoon` release to a specific `modules` commit (which we moved away from model, because it's *super-cool* being able to get fresh modules), so the following lines could also be deleted from `zoon.R`:

```r
# name a specific sha for a state of the modules repo, for tagged
# versions of zoon, or 'master' for non-tagged versions
# .sha <- 'b1544fbadaa21c41b4b51922ae73e44923b890ed'
.sha <- 'master'
```

We can always replicate a specific state of the modules repo by putting the sha in place of `master` in `options('zoonRepo')`

**Comment by AugustT** [comment]
Agreed

**Comment by goldingn** [comment]
Working on this now. Just a note to say that the new behaviour will be to specify the repo in `options('zoonRepo')`, and the branch in  `options('zoonRepoBranch')` the defaults for these are:
```r
options('zoonRepo')
```
```
$zoonRepo
[1] "https://raw.githubusercontent.com/zoonproject/modules"
```
```r
options('zoonRepoBranch')
```
```
$zoonRepoBranch
[1] "master"
```

**Comment by AugustT** [comment]
Nice!
