### ISSUE TITLE
Authors of LocalRaster

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#296]
@timcdlucas We only allow one email address per module so that thier is a single point of contact. Can you advise how I should change LocalRaster to conform with this?

Currently:

```
#' @author Tim Lucas \email{timcdlucas@@gmail.com} and Samuel Bosch \email{mail@@samuelbosch.com}

```

**Comment by timcdlucas** [comment]
Ummm. I guess the email address implies maintainer. Absolutely happy for @samuelbosch to take that if he wishes. If @samuelbosch doesn't want to be maintainer then I guess

    #' @author Tim Lucas \email{timcdlucas@@gmail.com} and Samuel Bosch

**Comment by AugustT** [comment]
Correct, the email address should be for the maintainer.

**Comment by AugustT** [comment]
Just for completeness the format would be like this

```
#' @author Tim Lucas, Samuel Bosch, \email{timcdlucas@@gmail.com}
```

**Comment by AugustT** [comment]
There has been no action on this so I have changed in line with my last comment
