### ISSUE TITLE
Travis builds failing

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#301]
This is a known issue with travis-ci and a fix is being worked on

https://github.com/travis-ci/travis-ci/issues/6139

**Comment by goldingn** [comment]
Now fixed at the travis end & `modules` (& my own repo that was failing) builds have successfully re-run.

The `zoon` build was still failing with:
```
$ git fetch origin +refs/pull/300/merge:
    fatal: Couldn't find remote ref refs/pull/300/merge
```
which is weird. I've opened a dummy PR to bump HEAD along one.

**Comment by goldingn** [comment]
that worked

**Comment by AugustT** [comment]
Thanks @goldingn I have sent the new version along to CRAN to ensure it is available in time for next week

**Comment by AugustT** [comment]
I have also added it as a release here

**Comment by goldingn** [comment]
I saw - great it's done already!

**Comment by AugustT** [comment]
First time ever a submission of mine to CRAN has gone straight through!

**Comment by timcdlucas** [comment]
Great success!
