### ISSUE TITLE
Workshop errors found

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#303]
mgcv
--------

    work1 <- workflow(occurrence = SpOcc,
                      covariate  = Bioclim(extent = c(-10, 10, 45, something)),
                      process    = Background(n = 1000),
                      model      = mgcv,
                      output     = InteractiveMap)

Two different errors

#309

**Comment by timcdlucas** [comment]
Categorical abundance
---------------------------------
Currently we have count abundance. Abundance categories requested

**Comment by timcdlucas** [comment]
Purge data function
---------------------------
Function to remove data from a workflow object.

**Comment by timcdlucas** [comment]
Stronger tracing of raster data
------------------------------------------
Raster metadata from *before* the zoon call?

Rasters with different resolutions
---------------------------------------------
Easiest way is a covariate module called `localRastersAndFixResolution`.
But further on we might want a meta module or a new verb or an argument or something.

**Comment by timcdlucas** [comment]
ZoonPredict
------------------
Passing a function is probably better than passing an expression.

Document that predict function should return response scale.

**Comment by timcdlucas** [comment]
Module submit function
---------------------------------
A function to submit a module directly to the repo.

**Comment by timcdlucas** [comment]
Workflow summary all arguments
----------------------------------------------
Easy: summary/report that documents all arguments (default and set) that was used in the workflow
Hard: All 'important' options set in the module.

**Comment by timcdlucas** [comment]
Just thought I'd add to the above.
I wonder if it's worth having a mechanism for documenting the *reasons* for the choice of parameters within a workflow object.
I'm sure it's unlikely people would use it.
But the aim is nice.

**Comment by AugustT** [comment]
# Dryad Module

Read in data using a DOI

**Comment by AugustT** [comment]
# Partial re-run workflow

An option to re-run a workflow from a set point (e.g. to re-create the side produces of an output module)

```
RerunWorkflow(workflow, from = 5)
```

**Comment by AugustT** [comment]
These should all be individual issues but I can do that after the workshop

**Comment by timcdlucas** [comment]
Yup. I started doing it wrong and then couldn't change. Kinda expected smaller "comments" but they all ended up being full blown issues.

**Comment by timcdlucas** [comment]
re "Partial re-run workflow" this is already there I think?
