### ISSUE TITLE
Missing module error has changed

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#308]
If a module was missing, you used to get an error "That module doesn't exist. Did you mean this..." or something like that.

Now I'm getting 
    Error in parse(text = rawText) : <text>:1:10: unexpected symbol
1: 404: Not Found

Nick reckoned something to do with the move to hacked roxygen function or something.

**Comment by AugustT** [comment]
Actually due to a change in httr == 'Not found' now '404: Not Found'. Doesn't look like it did the 'did you mean...'' stuff though. Fixed and will do PR
