### ISSUE TITLE
mgcv error

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#309]
work1 <- workflow(occurrence = SpOcc,
                      covariate  = Bioclim(extent = c(-10, 10, 45, something)),
                      process    = Background(n = 1000),
                      model      = mgcv,
                      output     = InteractiveMap)

Two different errors

**Comment by AugustT** [comment]
One error (at least) not related to mgcv. extractandcombine removes all occurrence points as all outside raster, this leads to error. Working on more informative error message.

**Comment by AugustT** [comment]
This seems to have fixed the issue
