### ISSUE TITLE
Rasters with different resolutions

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#313]
Easiest way is a covariate module that does `localRastersAndFixResolution`.
i.e. Read in two local raster and reduce resolution to lowest resolution.

But further on we might want a meta module or a new verb or an argument or something.

**Comment by AugustT** [comment]
Is this another instance of `aggregate`? Maybe not, as you are not combining them, more standardising them. 

I see this actually as a process module. Obviously `extractandcombine` will already have happened before the process module is run but it can simply coarsen the raster and then overwrite the extracted values in the occurrence table.

**Comment by timcdlucas** [comment]
Yes I think I see it as a process module ultimately. 

However, rasters are stacked even before `extractandcombine` (if they are from different modules `Chain`ed together). However, they can't be stacked unless they are the same dimensions. If you have the same area, with different resolutions, the dims will be different and stacking with fail.

**Comment by goldingn** [comment]
This is similar to #285. If the rasters don't have the same layout and CRS, zoon could fix them on the fly. I agree that a module would be better if we can make it work though

**Comment by AugustT** [comment]
This is being addressed in #285
