### ISSUE TITLE
Workflow summary all arguments

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#316]
Easy: summary/report that documents all arguments (default and set) that was used in the workflow
Hard: All 'important' options set in the module.

**Comment by AugustT** [comment]
The Hard version could be labled 'near-impossible'. This would require either module writers to explicitly say all the internal defaulots that they use or some super-smart function to be able to scrap this information.

The Easy version I like. We can adapt the summary.zoonWorkflow method to this purpose. I kinda like the idea of this being an HTML document but maybe that is overkill...

**Comment by timcdlucas** [comment]
Yeah I agree I can't see how the hard version would work at all.

I think the summary is a good idea.

**Comment by goldingn** [comment]
agreed!

**Comment by AugustT** [comment]
Hey Folks,

I've been spending quite a bit of time working on this. I have created a summary function that creates and launches an HTML report. This report is broken down into modules and present previews of the data in tables and plots. It should cope fine with lists and chains and uses a methods look-up to try and work out want to do with output modules. This is the sort of thing that I am producing:

Extract the zip to ensure the images work
[file25b0161776d9.zip](https://github.com/zoonproject/zoon/files/459207/file25b0161776d9.zip)

Considering the amount of time I have spent on this so far I am now going to leave this as it is. I have written in a fairly modular style so if anyone wants to improve on the design they should be able to without too many issues.

PR soon.

Tom

**Comment by timcdlucas** [comment]
Looks great!

Typo in:
"Predection code:"

But other than that I think it's just really useful. Is the function called `summary` or like `htmlsummary`? I guess I would expect summary to print just a quick text summary to the console.

**Comment by AugustT** [comment]
Thanks for spotting the typo. At present this is the `summary` method for a zoonWorkflow class object.

**Comment by timcdlucas** [comment]
OK. My two cents is that I'd find it annoying having a browser tab launch whenever I ran summary on the object. I would run `summary(model)` as a reflex every time I couldn't quite remember what was in it. I'd only want to see the big, detailed (and excellent) summary every now and then.

The risk then is that people might not find out about the function.

**Comment by AugustT** [comment]
If users want to see a smaller summary they have two other options, the print and plot methods

```r
work2 <- workflow(occurrence = UKAnophelesPlumbeus,
                  covariate = Chain(UKBioclim,UKBioclim),
                  process = Background(n = 70),
                  model = LogisticRegression,
                  output = SameTimePlaceMap)

work2
```
```
zoonWorkflow Object
===================

Call: workflow(occurrence = UKAnophelesPlumbeus, covariate = Chain(UKBioclim, UKBioclim), process = Background(n = 70), model = LogisticRegression, output = SameTimePlaceMap, forceReproducible = FALSE) 
```

```r
plot(work2)
```
![image](https://cloud.githubusercontent.com/assets/3987564/18319737/eea237e8-751e-11e6-9c97-3fce147b7414.png)


I think I would be more worried that people didn't know about the function than people getting frustrated with a browser window opening. I actually like the browser opening up as it give a big window in which to visualise the workflow details.

**Comment by timcdlucas** [comment]
Yeah print and plot are both good. Go with `summary`.

**Comment by goldingn** [comment]
This is great! Good work!
