### ISSUE TITLE
Does BuildModule keep comments

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#323]
Do they get stripped?

    z <- function(){
      # some comments
      return(2)
    }

    z

does keep the comments.

**Comment by goldingn** [comment]
`BuildModule()` uses `dput` to convert the function to text.

```r
dput(z)
```
```
function () 
{
    return(2)
}
```

But we can instead do:

```r
dput(z, control = 'useSource')
```
```
function(){
# some comments
return(2)
}
```

**Comment by timcdlucas** [comment]
Excellent. Let's do that.

**Comment by goldingn** [comment]
It annoys me that this loses the tabs

**Comment by goldingn** [comment]
also, it looks like we can just do:
```r
capture.output(z)
```
in `BuildModule()` and skip a step

**Comment by goldingn** [comment]
This adds a dependency, but it works:
```r
src <- capture.output(z)
src <- paste0(src, collapse = '\n')
tmp <- formatR::tidy_source(text = src,
                            indent = 2,
                            output = FALSE)$text.tidy

cat(tmp)
```
```
function() {
  # some comments
  return(2)
}
```

**Comment by goldingn** [comment]
I have no advance on this.
I say keep the dependency (`formatR` has no other dependencies). Keeping comments and indentation for readability is worthwhile.

**Comment by timcdlucas** [comment]
I'm happy with that. 
It doesn't make much a difference but `knitr` depends on `formatR` and `knitr` is in suggests anyway.

Longer term, knitr may be useful for building some sort of report.
So as far as extra dependencies go, this isn't a biggie.

(p.s. you weren't joking when you said you were getting up early!)

**Comment by AugustT** [comment]
@goldingn 

I dont have the problem that you demonstrate with the loss of tabs can you confirm that this does not produce a properly formatted file?

```r
 object <- function(){
   # some comments
   return(2)
 }

 obj <- deparse(substitute(object))

  # get and format the source code
  src <- capture.output(dput(object, control = 'useSource'))
  src[1] <- sprintf('%s <- %s', obj, src[1])
  src <- paste0(src, collapse = '\n')

  # get the file path and write to disk
  fpath <- paste0("./", obj, ".R")
  cat(src, file = fpath, append = TRUE)
```
For me this writes a formatted file

```r
object <- function(){
    # some comments
    return(2)
}
```

If this doesn't work for you this could be a windows/linux thing

**Comment by goldingn** [comment]
Yeah, I just ran your code and it returns a file with no indentation on my mac.

Let me know if it would be useful for me to try on Linux too

**Comment by AugustT** [comment]
Yes, please have a go on Linux. What do you think the underlying issue is here? I didn't think these systems would interpret tabs/white spaces differently?

**Comment by goldingn** [comment]
Huh, I'm not sure why, but I now get:

OSX RStudio:    indentation & comments
linux RStudio-server:    indentation & comments

OSX interactive command line R:    indentation & comments
linux interactive command line R:    indentation & comments

OSX RScript:    no indentation & no comments
linux RScript:    no indentation & no comments

I presume it's something to do with RScript putting output somewhere different, and probably easy enough to ignore. Would be interested whether RScript behaves the same on Windows.

I'm not 100% sure why I didn't get the tabs on OSX etc. when I first ran this, or the other day. I wonder if there's some other variable...

Either way, not worth worying about if neither of us can reproduce it any more
