### ISSUE TITLE
Allow NAs in occurrence module output

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#330]
Having all lat-long column values as NA my be sensible in some places. Instead of errors here there should be warnings reported such as x number of rows have NA values in column y. This needs changes inteh tests for modules and should be implemented on the website

**Comment by RTbecard** [comment]
The first few lines in the `ExtractAndComb` function strip the `NA` lat/lon points from the dataset, so this would also have to be updated.  Lines 364-372 in `zoonHelpers.R`.
