### ISSUE TITLE
User defined attributes in df not propagated

### ISSUE THREAD

**Issue by RTbecard** [zoonproject/zoon#331]
User defined attributes (as opposed to hard-coded attributes like `covCols`) don't propagate through the workflow.

In line 387 (zoonHelpers.R), the `cbind` strips the attributes, and user defined attributes in occurrence of process modules never get recovered (only the `covCols` attribute get recovered).

I'll write up a pull request for this today or tomorrow, as fixing this is necessary for allowing support of detection models.

**Comment by AugustT** [comment]
Did you get anywhere with this @RTbecard ?

**Comment by RTbecard** [comment]
yes!  I have it done and working a while ago!  I've held off on giving a PR, as I saw you guys were taking a break and I wanted to be sure it was working quite well by thoroughly testing it on my data.

I'll do a PR tonight, as I'll have to look over it and make sure the branch is clean and i haven't added any extra unnecessary stuff since then (commenting out try catch clauses etc.).

**Comment by AugustT** [comment]
Great stuff!

**Comment by RTbecard** [comment]
If you want to take a peek before then, its in my `SimulatedData` [branch](https://github.com/RTbecard/zoon/tree/SimulatedData).

**Comment by goldingn** [comment]
:+1:

**Comment by AugustT** [comment]
I think this should be closed
