### ISSUE TITLE
BiomodModel - fails tests

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#336]
Can anyone shed light on this? @timcdlucas 

The BiomodModel module intermittently fails testing and I can't figure out why:

```r
# PASSES
w <- workflow(occurrence = NaiveRandomPresenceAbsence(n = 1000, seed = 125),
              covariate = NaiveRandomRaster,
              process = NoProcess,
              model = BiomodModel,
              output = PrintMap,
              forceReproducible = FALSE)

# FAILS
w <- workflow(occurrence = NaiveRandomPresenceAbsence(n = 1000, seed = 123),
              covariate = NaiveRandomRaster,
              process = NoProcess,
              model = BiomodModel,
              output = PrintMap,
              forceReproducible = FALSE)

Caught errors:
Error in (function (cl, name, valueClass) : assignment of an object of class “NULL” is not valid for @‘val’ in an object of class “BIOMOD.stored.array”; is(value, "array") is not TRUE
```

**Comment by timcdlucas** [comment]
Hi,

I ran through line by line and the error occurs in the main call 

```
myBiomodModelOut <- BIOMOD_Modeling(biomodData,
```

according to this [thread](https://r-forge.r-project.org/forum/forum.php?thread_id=28893&forum_id=4342&group_id=302) the error is basically a really unclear way of saying the model didn't fit properly (perhaps predicted presence or absence at all locations).

For example I can get the model to run with 

```
     myBiomodOptions <- BIOMOD_ModelingOptions(
                           GLM = list( interaction.level = 1))

  myBiomodModelOut <- BIOMOD_Modeling(biomodData,
                                      models = modelType,
                                      models.options = myBiomodOptions,
                                      NbRunEval = 1,
                                      DataSplit = 100,
                                      Prevalence = 0.5,
                                      VarImport = 0,
                                      SaveObj = TRUE,
                                      rescal.all.models = TRUE,
                                      do.full.models = FALSE,
                                      modeling.id = id,
                                      silent = TRUE)
```


Fixes
--------

The quick fix would be to test the module with 
```
w <- workflow(occurrence = NaiveRandomPresenceAbsence(n = 1000, seed = 123),
              covariate = NaiveRandomRaster,
              process = NoProcess,
              model = BiomodModel(modelType = c('GLM', 'FDA')),
              output = PrintMap,
              forceReproducible = FALSE)
```

or if testing requires no arguments, make the default argument be two fast models.

In the longer term, it'd be good to put this main model call into a trycatch and return a less opaque error message if this error occurs (though this doesn't actually fix the testing issue).

**Comment by AugustT** [comment]
Do you think the underlying functions have change significantly? I now get other failures for this module

## Crossvalidate
```r
w <- workflow(occurrence = NaiveRandomPresenceAbsence(n = 1000, seed = 123), 
              covariate = NaiveRandomRaster,
              process = Crossvalidate,
              model = BiomodModel(modelType = 'GLM'),
              output = PerformanceMeasures,
              forceReproducible = FALSE)
```
```
Caught errors:
Error in (function (cl, name, valueClass) : assignment of an object of class “NULL” is not valid for @‘val’ in an object of class “BIOMOD.stored.array”; is(value, "array") is not TRUE
```

## Predicting

This module goes against the principle that ZoonPredict will produce a vector of values the same length as `newdata`. When 2 models are listed that x2 values are produced. This makes sense in isolation but won't work in zoon. The fix could be to only allow users to select one model type and then they can list these.

```r
work1 <- workflow(occurrence = UKAnophelesPlumbeus,
                  covariate = UKAir,
                  process = Background(n = 70),
                  model = BiomodModel(modelType = c('GLM','FDA')),
                  output = SameTimePlaceMap)

Caught errors:
Error in setValues(pred_ras, pred): length(values) is not equal to ncell(x), or to 1
```

**Comment by timcdlucas** [comment]
Crossvalidate
-------------------

I did about 10 runs with different seeds and got errors on 3-4 of them. So that is pretty annoying. 

OK. It's because biomod does AIC stepwise selection by default. Using these random rasters probably means all variables get removed or something.

I don't think stepwise selection should be a default option (push for LASSO instead anyway). So [line 44](https://github.com/zoonproject/modules/blob/master/R/BiomodModel.R#L44) in BiomodModel should become

      myBiomodOptions <- BIOMOD_ModelingOptions(GLM = list(test = 'none'))

This fixes your test issues.

However, I really think there should be an extra argument to this module allowing these options to be set.  i.e. 

```
BiomodModel <- function(.df, modelType = 'GLM', options = BIOMOD_ModelingOptions(GLM = list(test = 'none'))){

# other code

myBiomodOptions <- options

```

or something. If you don't get round to doing this I will try to.


Predicting
--------------

Agree, should be one only. Probably want a `biomodensemble` module at some point though.
