### ISSUE TITLE
on.exit behaviour changed

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#337]
`on.exit` has had a change to its behaviour which means that it can no longer modify the returned object. The result is that on failure the partial workflow is not returned

```r
testf <- function(x){
  
  y <- 'tom'
  on.exit(return(y))
  
  if(x>5){ stop('x is too big')}
  
}

out1 <- testf(6)
#Error in testf(6) : x is too big

out1
#Error: object 'out1' not found
```

This is a big shame as it makes debugging much more difficult. I have not been able to find a work around but will continue to look into it.

**Comment by AugustT** [comment]
I could fix this by assigning an object to the global environment

```r
testf <- function(x){
  
  y <- 'tom'
  on.exit({
    cat('The process failed. The partially completed workflow has been',
        'returned to your environment as an object named "zoonFailedWorkflow"')
    zoonFailedWorkflow <<- y
    })
  
  if(x>5){ stop('x is too big')}
  
  on.exit()
  return(y)
}

out1 <- testf(1)
out1
# "tom"
out2 <- testf(6)
#Error in testf(6) : x is too big
#The process failed. The partially completed workflow has been returned to your environment as an #object named "zoonFailedWorkflow"
out2
#Error: object 'out2' not found
zoonFailedWorkflow
#"tom"
```

What do we think to this? I hink this is an okay workaround as the user is very unlikly to have such a variable in their workspace. I'm not sure if CRAN likes `<<-` though

**Comment by timcdlucas** [comment]
I seem to remember CRAN specifically dissallowing assignment to the global environment. 
If someone decides to create `zoonFailedWorkflow` and it then get's overwritten, that could be really annoying for example.

I think I originally wrote it to assign an object in a new environment called `zoonOutput` or something? It wasn't a great solution though because the user had to know about this secret new object.

**Comment by timcdlucas** [comment]
My mistake. I had it written to assign to the global environment.

https://github.com/zoonproject/zoon/commit/2b0a7aa5e2eeb468f52fe53cc4e3517161985e98#diff-9dd63cc2d6a43b459b8929da40ddcc40R287

Still think CRAN don't like it.

**Comment by AugustT** [comment]
Yeah in checks I get...

```
checking R code for possible problems ... NOTE
workflow: no visible binding for '<<-' assignment to
  'zoonFailedWorkflow'
```

**Comment by goldingn** [comment]
Euurgh. So annoying.
Another option is tryCatching each module type, issuing the errors as warnings and returning rhe partial object.

**Comment by AugustT** [comment]
What about this. The partial workflow is saved as a temporary file and the users is told how to load it in.

```r
testf <- function(x){
  
  partialWorkflow <- 'tom'
  on.exit({
    tempf <- tempfile(fileext = '.rdata')
    save(partialWorkflow, file = tempf)
    cat(paste('The process failed. The partially completed workflow has been',
              ' saved as a temporary file. Load using "load("',
              normalizePath(tempf, winslash = '/'), '")"',
              sep = ''))
  })

  if(x>5){ stop('x is too big')}
  
  on.exit()
  return(y)
}

out1 <- testf(1)
out1

out2 <- testf(6)
out2
```

**Comment by AugustT** [comment]
I'm going with my suggestion for the moment. we could change this in the future (PR soon)

**Comment by goldingn** [comment]
Sounds like a good option for now.

Another possible alternative:

We may be able to write to the global environment without `<<-` (and thus avoid CRAN's checks) like this:

```r
foo <- function () {
  attempt <- 'blah'
  on.exit({
    e <- globalenv()
    e$.failed_workflow <- attempt
    message('\npartial zoon workflow saved in the object .failed_workflow\n')
  })
  stop('everything went wrong!')
}

foo()
```
```
Error in foo() : everything went wrong!

partial zoon workflow saved in the object .failed_workflow
```
```r
.failed_workflow
```
```
[1] "blah"
```

I haven't checked whether this passes the checks, & I'm not necessarily advocating for this (writing to global environment is still icky, but so's writing to disk), but worth considering
