### ISSUE TITLE
Module build fails

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#365]
There is currently a persistent failure on Travis for our modules. This is linked (I think) to the roll out of the new roxygen2 package which required some changes to `ZoonModuleParse`. I made these changes in the latest release to CRAN but I must have missed something. This all runs fine on my computer so I'm inclined to think it is a Linux issue. The error occurs at here: https://github.com/zoonproject/zoon/blob/master/R/ZoonModuleParse.R#L21 so something like this should replicate the error 

```r
URL <- "https://raw.githubusercontent.com/zoonproject/modules/master/R/MaxNet.R"

require(zoon)

pmod <- ZoonModuleParse(modulePath = URL)
```

or running tests on the module package.

As I say this does not produce an error on my machine. I don't think this is limited to Maxnet (which shows in the travis error log) as my fork, which doesn't have maxnet also fails with the same error. Can @goldingn and @timcdlucas have a look and see if they can replicate the error?

**Comment by timcdlucas** [comment]
Will try to get to it soon.

**Comment by goldingn** [comment]
I've lost access to my linux build environment, but I'm testing on OSX now

**Comment by goldingn** [comment]
The code snippet works fine on OSX, and I don't get that error in the tests (I do another errors, which I'll post as a separate issue)

**Comment by goldingn** [comment]
I just tried this on a linux box and it works fine for me

**Comment by goldingn** [comment]
To clarify, that code snippet you provided works fine on my linux machine (and my OSX)

However, I've just run `devtools::test()` on the package on linux and can repeat the error. It doesn't occur in maxnet (that was just the last package loaded), but in `TargetGroupBackground`

This replicates the error on linux and OSX:
```r
URL <- "https://raw.githubusercontent.com/zoonproject/modules/master/R/TargetGroupBackground.R"
require(zoon)
pmod <- ZoonModuleParse(modulePath = URL)
```

**Comment by goldingn** [comment]
I think this is a fix, but expect that PR to fail because the GBIF API seems to be wigging out at the moment

**Comment by goldingn** [comment]
oooh, it worked. closing this now
