### ISSUE TITLE
Distribute Maxent jar file with zoon

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#376]
Now there is an [open source release of Maxent](http://biodiversityinformatics.amnh.org/open_source/maxent/) (v3.4.0, MIT licence), I believe we can now distribute the jar file with an R package, provided the licence goes with the binary. Doing this for zoon would make it easier for users to install and run zoon.

I have just added the jar file to the `zoontutorials` package (mostly just to get travis to work) by putting the jar file, licence and readme [here](https://github.com/zoonproject/zoontutorials/tree/master/inst/java), and adding a `.onLoad()` function to copy the file into the right location for dismo [here](https://github.com/zoonproject/zoontutorials/blob/master/R/zzz.R).

I believe that is in line with both the spirit and the letter of the licence, but would appreciate your thoughts @AugustT @timcdlucas @GregMci before doing that here.

Taking the same approach as for `zoontutorials` would negate the `GetMaxEnt()` function we currently have, and the `Biomod` module could then copy the jar file to the working directory, use it, then delete it.

**Comment by timcdlucas** [comment]
That seems reasonable. The alternative is we bundle the source and build the binary locally and who's going to argue that that makes sense.

If it's a worry i guess a quick email to the owners would settle it...

**Comment by goldingn** [comment]
Cool.

R has no way of compiling java during package installation (only C++ & fortran are supported I think) so the source code alternative wouldn't work anyway.

An email to Steven Phillips sounds like a good idea!

**Comment by AugustT** [comment]
This sounds like a good idea and given the new license I see nothing to stop you going ahead. I don't think an email to the owners is needed, given the MIT license, but perhaps it will bring peace of mind. How does this affect our current license for `zoon`?

**Comment by goldingn** [comment]
Cool. I think it shouldn't affect our licence, neither MIT nor BSD are copyleft. But I'm not a lawyer
¯\_(ツ)_/¯

**Comment by AugustT** [comment]
Yeah, I think your right. Licences huh... almost as confusing as regular expressions.

**Comment by goldingn** [comment]
Note to self, for the biomod module we should be able to use something like this to point to the file (rather than copy to the working directory as they suggest):

```r
maxent_path <- system.file('java/maxent.jar', package = 'zoontutorials')
biomod_options <- BIOMOD_ModelingOptions(MAXENT.Phillips = list(path_to_maxent.jar = maxent_path))
BIOMOD_Modeling(..., models.options = biomod_options, ...)
```

**Comment by timcdlucas** [comment]
This is an old issue... and things have changed. But I found it while browsing.

As MaxEnt is now MIT, I think we can bundle if we wish. But it's probably a fair bit of effort. My preference in general is to switch to the MaxNet as the "go to". 

So, I'll close this issue. Obviously anyone can feel free to reopen.
