### ISSUE TITLE
Buildmodule helpfile 'diagnostic' type

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#377]
The helpfile for `BuildModule()` gives the following for `type`:

> A string that defines the type of module. Possible module types are occurrence, covariate, process, model, **diagnostic** and output.

I'm not sure where diagnostic came from, I don't even remember that phase of zoon!

**Comment by AugustT** [comment]
no idea!

**Comment by timcdlucas** [comment]
Ha, original commit for the file.
https://github.com/zoonproject/zoon/commit/322109ec216bd9e7483c761a383f68467615cab5#diff-53c5ac98dcb857e73a8bced93ea998fe

It's also in checks for module type.
https://github.com/zoonproject/zoon/blob/e44f8ca1d45df3cd3c176829fc4f2552dbf13174/R/BuildModule.R#L50

whoops.

**Comment by AugustT** [comment]
Kinda surprised I never noticed this!

**Comment by goldingn** [comment]
me too!
