### ISSUE TITLE
seegMBG code

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#382]
Hi @goldingn.

Currently in my INLA module I'm using plenty of code from seegMBG (getting predictions from inla models is a pain.) 

So a) Did you write this code? Git commits say yes. There's no license so is there anyone else I need to consult before copying the code.

b) Is acknowledgement in the source code and in the module details sufficient?

c) The zoon modules repo is MIT. Are you happy for that to be applied the code

d) Longer term,  I'm also writing this [INLAutils](https://github.com/timcdlucas/inlautils) package which I intend to put on CRAN at some point. Seems like it's a useful reuse of code to encorporate the `inlapredict` functions into there as well. If you're happy for me to do that I will do so. Again, can acknowledge you or add you as an author to the package. Whichever you prefer.

**Comment by goldingn** [comment]
a) yep, twas me. I'm still using in a couple of of projects. Sure there's a
license: https://github.com/SEEG-Oxford/seegMBG/blob/master/DESCRIPTION#L11
Copyleft unfortunately, so won't play nice with MIT.

b) I'm no lawyer, but I reckon adapting it and saying (in code comments)
your code is 'inspired' by that code, that could work. It's certainly fine
by me. Legally I guess it depends how similar the new code is.

d) sure, happy for it to be reused as much as possible.

I seem to still be the owner of SEEG-Oxford. Would you like to take over
ownership, seeing as you're still in the group (sort of) and I'm not?

**Comment by timcdlucas** [comment]
a) Oh yeah, I just assume there'll be a license file. 

b) OK that sounds the easiest first step. As the copyright owner only YOU can prosecute me for copyright infringement... so as long as you don't take me to court, it's all fairly fine. Longer term it might be neater anyway to get a version into INLAutils, get that on CRAN then get the INLA module to use that... but I was hoping this would be a quick project!

b2) Or maybe, all these issues disseapper if I take the time to get seegMBG onto CRAN (do it from my fork, maybe add myself as an author). Then I can just easily use it, no licensing issues involved.


d) Same MIT vs GPL issues apply here. So I'll have a think how best to deal with it. Same as above, maybe I should just get it on CRAN. Thanks!


I did discuss this with people at MAP. As seeg no longer exists, there seemed little point. I've forked seegMBG and might fork seegSDM as well just so there's definitely copies. So in short, it seems that forking/renaming/copying over code is simple than taking ownership. Seem reasonable?

**Comment by goldingn** [comment]
Cool sounds like a plan. I hereby promise I won't sue you for copyright
infringement on seegMBG. Pushing that to CRAN would work too, your call!

**Comment by timcdlucas** [comment]
OK, I'll have a play around. May well do a not-totally-clean code copy to get INLA module going. Then later, slower, go about getting seegMBG onto CRAN. It depends on seegSDM, so that's not trivial either. Sigh.

**Comment by timcdlucas** [comment]
While we're here, would you want to be maintainer of seegMBG on cran? Or specifically not want to be? You'll be first author either way obviously.

**Comment by goldingn** [comment]
Nah, happy for you to maintain. I only wrote it for a couple of projects,
one's pretty much done and the other should be dobe within the year. Moving
away from INLA after that :)

Glad it's been useful to you!
