### ISSUE TITLE
Change the default zoom level in InteractiveMap?

### ISSUE THREAD

**Issue by Doi90** [zoonproject/zoon#385]
Is there a way to change the default zoom level in leaflet maps like the InteractiveMap module? 

I hadn't really noticed it while we've been using the Carolina Wren data in the tutorials, but with the switch to Joshua Tree in the basic workflow example it is really apparent that it is quite zoomed out. I guess the rasters being effectively square makes it more noticeable.

It seems like a lot of wasted space to me. The only reason I can see is that it makes people utilise the "interactiveness" of the map by having to zoom in straight away. Having the map load with the prediction taking up as much of the screen as possible without being cropped would make more sense to me (or with maybe a 10% buffer of the underlying street/satellite map around the edge to keep the "interactiveness" apparent).

I have noticed that the zoom seems to have discrete levels rather than a continuous range (and for both datasets I mentioned zooming in one level is enough to start putting parts of the prediction off-screen), so maybe the amount of control we have is limited anyway? Especially since there are rather significant changes in zoom between one level and the next.

Any thoughts?

**Comment by timcdlucas** [comment]
I guess default should be the range of the presence-absence (or whatever) data. Don't know how easy it is to set though.

**Comment by AugustT** [comment]
Doesn't sound easy to me. I think it just has a zoom parameter with is on a scale of 1-12 or something. If there was an xlim ylim type argument that would make it easier but I don't think there is...

**Comment by Doi90** [comment]
Yeah, seems to just have the zoom parameter set on an integer scale. I've gotten past the issue for the vignettes by tweaking the extents of the data as it just picks whichever scale is the first one to fit everything on the screen at once. This way there is less wasted space in the examples we're using. That will do for now
