### ISSUE TITLE
Subsetting GetModuleList()

### ISSUE THREAD

**Issue by Doi90** [zoonproject/zoon#386]
It would be good if we could subset GetModuleList() with an argument rather than sub-setting a saved list. If I want to see just occurrence modules then I need to run this:

```
tmp <-GetModuleList()
tmp$occurrence
```

Ideally we could do something like this:

```
GetModuleList(type = "occurrence")
```

Makes it neater when using it in the vignettes we're building.

**Comment by AugustT** [comment]
Sounds like a good idea to me

**Comment by timcdlucas** [comment]
I certainly tried (and clearly failed) to do this back in the day. `GetModuleList` downloads the .Rd files.  I think the only bit in there that guarantees to  identify the module type is

`Other process: \code{\link{AddRandomUniformPredictors}},`

Does that seem right @AugustT ?

**Comment by AugustT** [comment]
I was thinking much more simple than that. Put type in at the end 

```r
GetModuleList(type = "occurrence"){
    ...
    return(tmp[type])
}
```

But then I am a  lazy coder!

There might be a way to identify all the correct .rd files and then just download them, which would obviously be more efficient. But the .rd files are pretty small at the moment...

**Comment by timcdlucas** [comment]
Oh right! Forgot `GetModuleList` does already do the grouping. Yup, your way sounds fine,

**Comment by goldingn** [comment]
Sounds ace. Want to take a swing at implementing this @doi90? 

If so, check out `match.arg()` for type checking the argument.

**Comment by Doi90** [comment]
I'll swing away.

**Comment by Doi90** [comment]
Submitted a pull request with the ability to subset by module type. Assuming it passes Travis checks and people are happy with my approach I'll close this issue

**Comment by goldingn** [comment]
this is in master now
