### ISSUE TITLE
Chain is not a real function

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#41]
In fixing #40 we have prevented execution of functions given to arguments.

The easiest way to tell between list(mod1, mod2), Chain(mod1, mod2) and mod1 is to simply see if the first element of the substituted argument is 'list', 'Chain' or something else.

I think there's probably some reason why this is bad coding style.

Furthermore it means Chain is not a function that is ever actually called. It need documentation though. So perhaps I need to make a phantom function or something.

**Comment by goldingn** [comment]
The documentation for this could be improved, I imagine it's something the workshop users will want to check out. Adding this as a milestone for that reason.

Could we define the following function, even if it isn't actually used internally:
```r
Chain <- function (...) {
  ans <- list(...)
  attr(ans, 'isChain') <- TRUE
  return (ans)
}
```

There's also an argument and making `Chain` `chain` for consistency with `list`

**Comment by goldingn** [comment]
I'm going to do the thing I suggested above later today, unless someone objects

**Comment by timcdlucas** [comment]
I'm happy. Probably worth mentioning in the docs that it isn't actually used as a function.
