### ISSUE TITLE
vignette error

### ISSUE THREAD

**Issue by trashbirdecology** [zoonproject/zoon#427]
The following function is not available but is called in a [vignette](https://github.com/zoonproject/zoon/blob/0.6/vignettes/interactive_zoon_usage.Rmd)

> ```r
> proc <- OneHundredBackground(data)
> ```

**Comment by timcdlucas** [comment]
Hi,

The `LoadModule` call in this line should load that function from GitHub.

https://github.com/zoonproject/zoon/blob/bf10f8f72b6c6d23ec81cc51e8dc3555bc5d17a3/vignettes/interactive_zoon_usage.Rmd#L69

Hope that helps.

**Comment by trashbirdecology** [comment]
feel free to resolve if this works, i was just testing the vignette and don't have plans to go back through it! 

thanks

**Comment by timcdlucas** [comment]
No problem. Nice to know people are looking at the package!
