### ISSUE TITLE
Sort modules by type in GetModuleList

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#43]
I don't know how to do this but I think we need to add metadata to the roxygen comments and sort by that.

First thoughts are that we don't want to read the text of every module just to print a list of modules. So I'm not sure how to fix this. 

Once continuous integration is sorted, it might be easiest to do a nightly run of reading each file, reading the meta data and making a separate file with the module list. GetModuleList() then simply needs to read that file. This also fixes the requirement for a github password to use GetModuleList.

**Comment by goldingn** [comment]
Is it possible to have roxygen2 (or similar collate) a .Rd or similar which lists the modules and their metadata?

From that it should be possible to download a single file with all this information present. It would also remove the need for GitHub oauth credentials when querying this stuff.

I think that'll be pretty important for novice users.

**Comment by goldingn** [comment]
If we add a `@family` tag in the Roxygen for each module, giving the module type, then a list of other modules of the same type will be added to all module help files. We would then only have to download the `.Rd` for a known module of each type and scrape the module lists from the bottom of each.

This would give a structured list in `GetModuleList` and (hopefully) enable us to avoid the github auth stuff as R >=3.2.0 will download from https

**Comment by goldingn** [comment]
This (the `@family` tag thing) is implemented in modules now.

I've written some draft code to replace `GetModuleList` by scraping the modules available in each type from these help files. I don't have time to finish the job now, so I've pasted the code in case someone wants to pick this up.

Once this is in place we can remove caching of credentials and dependencies on `httr`, `httruv` and probably `RCurl`

```r
# obviously this bit won't be needed when the code is in the package...
library(zoon)
DownloadQuietly <- zoon:::DownloadQuietly

# modules we know belong to each type (doesn't matter which they are,
# but these should be fairly stable)
canaries <- c(occurrence = 'SpOcc',
              covariate = 'Bioclim',
              process = 'NoProcess',
              model = 'LogisticRegression',
              output = 'InteractiveMap')

# get URLs for these modules
canary_urls <- helpURL <- paste0('https://raw.githubusercontent.com/zoonproject/modules/master/man/',
                                 canaries,
                                 '.Rd')

# empty list for results
results <- list()

for (i in 1:5) {
  
  # grab the rd file
  rd_i <- readLines(url(canary_urls[i], method = 'libcurl'))
  
  # get te expected module type
  type <- names(canaries)[i]
  
  # find the starting line
  start_line <- grep(sprintf('^Other %s: ', type), rd_i)
  
  # find all section -closing parentheses
  end_lines <- grep('^}$', rd_i)
  
  # find the end of this section
  end_line <- min(end_lines[end_lines > start_line])
  
  # grab the required lines and combine
  text <- paste(rd_i[start_line:end_line],
                collapse = '')
  
  # remove formatting we don't want
  start_text <- sprintf('^Other %s: ', type)
  text <- gsub(start_text, '', text)
  text <- gsub('\\\\code\\{\\\\link\\{', '', text)
  text <- gsub('\\}', '', text)
  
  # split into vector
  text <- strsplit(text, ';')[[1]]

  # add the target module in
  text <- sort(c(canaries[i], text))
  
  # remove any names
  names(text) <- NULL
  
  # remove spaces
  text <- gsub(' ', '', text)
  
  # add to results
  results[[i]] <- text
}

results
```

```
$occurrence
[1] "CWBZimbabwe"         "LocalOccurrenceData"
[3] "UKAnophelesPlumbeus" "AnophelesPlumbeus"  
[5] "SpOcc"              

$covariate
[1] "LocalRaster" "UKAir"       "NCEP"        "UKBioclim"  
[5] "AirNCEP"     "Bioclim"    

$process
[1] "Background"              "Crossvalidate"          
[3] "OneHundredBackground"    "OneThousandBackground"  
[5] "PartitionDisc"           "BiasBackground"         
[7] "BackgroundAndCrossvalid" "NoProcess"              

$model
[1] "MaxEnt"             "mgcv"              
[3] "QuickGRaF"          "GBM"               
[5] "OptGRaF"            "RandomForest"      
[7] "BiomodModel"        "LogisticRegression"

$output
[1] "InteractiveCovariateMap" "PerformanceMeasures"    
[3] "PredictNewAreaMap"       "ResponseCurve"          
[5] "SameTimePlaceMap"        "PrintMap"               
[7] "SurfaceMap"              "Figshare"               
[9] "InteractiveMap"
```
