### ISSUE TITLE
tmpZoonWork returned from workflow, not saved to global object

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#51]
tmpZoonWork <- ErrorAndSave(...)
return(tmpZoonWork)

instead of global assignment i.e. assign('tmpZoonWork', w, env = 'GlobalEnv()) or whatever it is.

**Comment by goldingn** [comment]
This came up in the last workshop.

I think the error can just modify the output to be `NULL` without too much bother. Then it should be fine to just return the object.

I think it would be great to have this ready for the training workshop

**Comment by goldingn** [comment]
this is covered by #104 so closing this one. It isn't super-important for the training workshop
