### ISSUE TITLE
breakeable 6:ncol(df)

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#53]
Is used in ExtractAndCombine. Probably other uses are in modules.

In ExtractAndCombine can simply assign names tom environmental vars before cbind with rest of df.

**Comment by AugustT** [comment]
@timcdlucas Can you clarify what the problem is here? What is breakable about `6:ncol(df)`?

**Comment by timcdlucas** [comment]
I can't quite remember. I think we added an extra column and had to go through and change 5:ncol(df) to 6:ncol(df). The same thing could happen again. 

But breakable is probably the wrong word, we're less likely to add columns and the ways to fix it aren't appealing either.

I'll close.

**Comment by goldingn** [comment]
Yeah, I think this was just to note that a  better pattern might be to select those columns not matching the expected column names. I.e. something like (but preferably shorter than):

```r
covariate_columns <- df[, !(column_names %in% vector_of_expected_column_names)]
```
```r
covariate_columns <- df[, 6:ncol(df))]
```

Doesn't really need an issue though.
