### ISSUE TITLE
What  modules did the workflow use function

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#55]
Want a function just to easily and cleanly extract what modules have been used. Something like.
not sure where chain/list should go in this output.
w <- workflow(mod1, mod2, mod3, Chain(mod4, mod5), mod6)

WhichModules(w)
[1]
occurrence$
mod1

covariate$
mod2

process$
mod3

model$
mod4
mod5

output
mod6

**Comment by goldingn** [comment]
we have print and plot functions now, so I think this is redundant.
