### ISSUE TITLE
ChangeWorkflow doesn't work with parameter modules

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#57]
If the original workflow had modules with parameters

  w4 <- workflow(UKAnophelesPlumbeus,
                 UKAir, 
                 BackgroundAndCrossvalid(k=2),
                 RandomForest,
                 PerformanceMeasures)

And those modules remain, ChangeWorkflow doesn't work.

ChangeWorkflow(w4, model=LogisticRegression)

because BackgroundAndCrossvalid(k=2) gets turned into a string before it is parsed.

**Comment by AugustT** [comment]
Fixed in f6ba44b11c89618eff46b91037bf3ee81e40af14
