### ISSUE TITLE
Way call is saved and used by ChangeWorkflow

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#58]
Currently, the call is saved as a string. This is probably useful but we probably want to also save it in workflow output as a useuable list. 

ChangeWorkflow is a mess because it spends ages messing around sorting the string call out. Would be easier if there was something more structured.

This extra mess flows into SplitArgs, SplitCall. Might be other places as well.

I won't have time to do this, so just leaving this here.

**Comment by goldingn** [comment]
Re. the first point, we now have a `call.list` argument returned, which saves the call as a list of (lists of) lists giving the module and paras for each module type.

This would probably make ChangeWorkflow simpler, but I'm going to remove this issue and leave up issue #57
