### ISSUE TITLE
Submodule

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#63]
Just saw this and it might be a useful way to make the module and zoon repo slightly more attached.

Haven't thought this through at all.

Here is an example:
https://github.com/maxheld83/schumpermas

e.g. `civicon.github.io @ f24322f` is embedded within the maxheld83/schumpermas repo.

Here is info about submodules
http://git-scm.com/docs/git-submodule

Seems like it points to a specific commit and doesn't update. So maybe not useful.

**Comment by AugustT** [comment]
Good to keep in mind.

I'm going to close this for now
