### ISSUE TITLE
Piping

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#64]
Just been thinking about alternative pipe style syntax and thought I'd write it down here before I forget.

Given the pipeline nature of the workflow, I think this makes some sense. And depending on how it's written it could make running a workflow interactively easy.

I can see three ways:

## 1 easiest

Define inflex operators %1%, %2% etc. so a workflow would look like

    w <- UKAnopheles %1%
              UKAir %2%
              OneHundredBackground %3%
              LogisticRegression %4%
              PrintMap

The operators just capture the input and put them into a list. %4% then puts the list into workflow with do.call.

This should be easy to implement and requires no changes to the rest of the code. Nor any code duplication. However, it couldn't be used interactively.

## 2 Same syntax as above

This time, each of the inflex operators run a portion of the code in workflow (i.e. loads of code duplication). However, it means that for example

    w2 <- UKAnopheles %1%
               UKAir

Should return just the workflow up to that point. Or something. I suppose it doesn't have the benefit of saving output to objects, which is half the point of interactive usage. 

## 3 ggplot2 style + operator

    w <- UKAnopheles +
              UKAir +
              OneHundredBackground +
              LogisticRegression +
              PrintMap

It's very neat and obvious to pretty much everyone (not just magrittr/hadleyverse users).

Requires changes to `workflow()` such that the outputs of each step of the analysis get a class attr. Then define methods for `+.process`, `+.occurrence` etc.

I reckon I'll make a branch and try and implement option 1. Definitely won't do 3 as I don't want to mess with core code.

**Comment by timcdlucas** [comment]
See https://github.com/hadley/ggplot2/blob/4bb9270ef4d5d5062353438fd99d17b6f6de98a2/R/plot-construction.r for how the + operator is done in ggplot2.

**Comment by timcdlucas** [comment]
First naive attempt at option 1 above is added in 5d093db

w <- UKAnophelesPlumbeus %1%
          UKAir %2%
          OneHundredBackground %3%
          LogisticRegression %4%
          PrintMap

Now works.

**Comment by AugustT** [comment]
This is a neat idea! I always wondered how these worked under the hood. However I feel that the system we have in place now works well and is nice and explicit. Are you happy for me to close this issue?

**Comment by timcdlucas** [comment]
Yup I'll close.
