### ISSUE TITLE
Export functions needed to run interactively

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#65]
In the vignette for interactive usage, [here](https://github.com/zoonproject/zoon/blob/master/vignettes/interactive_zoon_usage.Rmd), we suggest using `zoon:::RunModels` and `zoon:::ExtractAndCombData`.

Should these functions be exported to make interactive use easier? Or not exported to keep the package simple for non-devs?

**Comment by AugustT** [comment]
I would export them if you expect someone to use them. Functions that are not exported are considered internal (ie not for use by the user).

**Comment by goldingn** [comment]
Yup. We could make clear in the docs that these are used internally and are exported to enable module developers to test stuff out - but they aren't likely to be useful for day-to-day zooning.

**Comment by AugustT** [comment]
Fixed in b7d7cd3faf8faf6ca1a81c91690e84fb50bfbbf9 will close after PR
