### ISSUE TITLE
ErrorAndSave export

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#66]
ErrorAndSave is currently exported and I'm pretty sure it shouldn't be.

**Comment by timcdlucas** [comment]
Oh wait. No I don't think it is.

However, I've documented a load of internal functions. When you build the pdf manual, these are all included. Not sure if CRAN will remove the unwanted functions.

**Comment by goldingn** [comment]
closing this as documentation is covered by #79
