### ISSUE TITLE
better errors from ExtractAndCombData

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#76]
When no occurrences fall on the raster (e.g. if the raster extent is misspecified), the error is pretty cryptic. This should be caught and handed to the user more clearly

**Comment by goldingn** [comment]
This is important UI stuff so adding to milestone

**Comment by AugustT** [comment]
is this fixed? I got a nice 'removing points outside extent' in a recent run I did'

**Comment by goldingn** [comment]
Oh yeah, looks like I fixed this on Thursday - must have forgotten to take it off the whiteboard before adding issues
