### ISSUE TITLE
Interactive map

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#77]
This would be really cool, particularly something along the lines of the `mapView` function in [this package](https://github.com/environmentalinformatics-marburg/Rsenal).

This can be made to work for some workflows, but when `SpOcc` is used, it loads `leafletR` first, which causes an error when using `leaflet`. All attempts at removing `leafletR` failed and `leafletR` can't plot rasters....

**Comment by goldingn** [comment]
I think the best approach in the short term will be to get around the issues specifically with loading `spocc`, or switching the `SpOcc` module to use e.g. `dismo::gbif`

**Comment by timcdlucas** [comment]
dismo::gbif uses an older gbif API (unless it's been updated.)
https://github.com/ropensci/spocc/issues/52

You essentially get fewer results. So that isn't ideal. 

Can we use spocc without attaching the package? 
 
' spocc::occ2df' rather than 'occ2df' does this I think?

**Comment by goldingn** [comment]
This may have changed since those comments - I know `dismo::gbif` stopped working for a while earlier this year, then started again, possibly due to switching API.

However your other suggestions sounds like a good one. We can edit `GetPackage` to install, but not load packages, and then try something along those lines.

**Comment by goldingn** [comment]
also worth adding the training data on top

**Comment by goldingn** [comment]
This is done with [a PR to modules](https://github.com/zoonproject/modules/commit/4eb65bb790e9118f062ad2044228e64b576bde8f), may try to tart it up with added training data later

**Comment by timcdlucas** [comment]
Just to say I can't get this new module to work.

    work2 <- workflow(occurrence = UKAnophelesPlumbeus,
                      covariate  = UKAir,
                      process    = OneHundredBackground,
                      model      = RandomForest,
                      output     = InteractiveMap)

gives

    Caught errors:
Error in raster::projectRaster(x, raster::projectExtent(x, crs = sp::CRS(epsg3857))): input projection is NA

**Comment by timcdlucas** [comment]
But this work:
    
    work2 <- workflow(occurrence = UKAnophelesPlumbeus,
                      covariate  = UKBioclim,
                      process    = OneHundredBackground,
                      model      = RandomForest,
                      output     = PrintMap)

So I guess UKAir does pass it's projection properly.

**Comment by goldingn** [comment]
yup, will add as a separate bug - thanks!

**Comment by AugustT** [comment]
The interactive map looks great! Good work.

I have a minor comment, the legend on my plot from:
```R
work2 <- workflow(occurrence = UKAnophelesPlumbeus,
                  covariate  = UKBioclim,
                  process    = OneHundredBackground,
                  model      = RandomForest,
                  output     = InteractiveMap)
```
... goes from 0-2, is this right? I feel like it should go from 0-1?

![image](https://cloud.githubusercontent.com/assets/3987564/9361265/7b9d8024-4692-11e5-8852-e86a035deffb.png)

**Comment by goldingn** [comment]
weird.... will check it out.

**Comment by goldingn** [comment]
So `mapView` just uses `leaflet::addLegend` with mostly default settings, and it looks like `addLegend` takes a guess at the range of values, not knowing they should be restricted to (0, 1].

I should be able to get around this by manually setting up the legend in the non-`mapView` version

**Comment by goldingn** [comment]
All solved in [this PR](https://github.com/zoonproject/modules/pull/18) - I enforced the (0,1] thing.

Only issue is the legend's still the wrong way up, but that's harder to fix than you'd think...

I consider this accomplished though
