### ISSUE TITLE
UKAir module has incorrect projection

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#86]
causes `InteractiveMap` module to fail. see Tim's examples [here](https://github.com/zoonproject/zoon/issues/77#issuecomment-132125376)

**Comment by AugustT** [comment]
I have had a go at this but could use some input from someone familiar with the data and rasters (something else I need to learn about!) @goldingn 

I changed the projection of the data to `+proj=longlat` and got this result.

![image](https://cloud.githubusercontent.com/assets/3987564/9361834/42acfc92-4695-11e5-904c-69d00bc27f64.png)

Is this correct? if so I will save over the package data file

**Comment by goldingn** [comment]
It's worth checking what RNCEP says it is, but I imagine it's wgs84, so: `+init=epsg:4326`
I think your version yields an identical result though.

**Comment by AugustT** [comment]
I see no reference to `UKAirRas` in RNCEP, and there is no documentation in `UKAir` stating how the data were generated (using RNCEP I assume?).

In the help documentation examples the authors repeatedly use '+proj=longlat + datum=WGS84' for exporting and building rasters and spatial object so I think this is probably the correct projection.

The resulting graph is essentially the same, I'll set this as the projection and update the data file

**Comment by AugustT** [comment]
Fixed in `a0bb5d7d3174c225275dc98362acfb83a1f137b6`
