### ISSUE TITLE
Chain order in plot.zoonWorkflow

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#90]
work1 <- workflow(occurrence = UKAnophelesPlumbeus,
                      covariate  = UKBioclim,
                      process    = Chain(OneHundredBackground, PartitionDisc),
                      model      = LogisticRegression,
                      output     = list(PerformanceMeasures, PrintMap))

    plot(work1)

gives me 
![zoonflow](https://cloud.githubusercontent.com/assets/3583796/9333295/02938efc-45c1-11e5-814f-8ce6fb8a457f.png)

which has the chain in the wrong order. 

Also anything that could be done to avoid text overflowing boxes would be great.

**Comment by goldingn** [comment]
Good catch. I think that just needs a `rev` somewhere. Will take a look at some point.
