### ISSUE TITLE
dependence on devtools

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#92]
Currently we don't have devtools in `Depends` or `Imports`. In part I guess that's because we don't want windows users to have top install RTools.

However `GetPackage` needs devtools if we're getting packages from GitHub (e.g. for `InteractiveMap`). This currently shows up as the following warning in check:

> `* checking R code for possible problems ... NOTE
GetPackage: no visible global function definition for ‘install_github’`

Should we bite the bullet and declare a dependency?
Or is there something we can do with an imports or suggests?

**Comment by goldingn** [comment]
Just noticed this is a duplicate of #47. Will close that one, but it's worth a read.

I think this might be what `suggests` is for, but need to re-read that bit in the manual.

**Comment by AugustT** [comment]
It is best to have the package pass with no warnings and no notes so this does need to be dealt with. Since this package is needed for this functions functionality (and therefore zoon) it would need to go in imports rather than suggests (as I understand it anyway!). Alternatively we could remove the ability to install from GitHub... or are there key packages you know of that are only available from github?

**Comment by goldingn** [comment]
I think you're right. From ['Writing R Extensions'](https://cran.r-project.org/doc/manuals/R-exts.html):

> In particular, packages providing “only” data for examples or vignettes should be listed in ‘Suggests’ rather than ‘Depends’ in order to make lean installations possible.

At the moment it's just `InteractiveMap` which depends on [`Rsenal`](https://github.com/environmentalinformatics-marburg/Rsenal) which is on github.

We could get around that by dragging code from there into `InteractiveMap` if the licensing is permissive and we attribute appropriately.

The question is really whether we want to make it easy for future developers to depend on more experimental GitHub-only packages. I suspect the answer is no...

**Comment by goldingn** [comment]
Will try to go down this route by solving #96 and then editing `GetPackage`

**Comment by goldingn** [comment]
On a related note, the metacran packages may be useful for getting old versions of packages from CRAN etc. Looks like another reason to depends on devtools though :) https://github.com/metacran/metacran/blob/master/README.md
