### ISSUE TITLE
Code style spaces in function calls

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#97]
I have noticed some variation here so let me know which is correct.

I normally write

    function(arg1 = 'x')

But I have seen in the code

    function (arg1 = 'x')

small point but I want to be consistent. What is our style?

Tom

**Comment by goldingn** [comment]
Officially it's [Google](https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml#functiondefinition), but ignoring the bits about where to comment a function that conflict with roxygen2.

So the first version is correct:

> GOOD:
> `PredictCTR <- function(query, property, num.days,
                       show.plot = TRUE)`

Those other ones may well have been me, so feel free to change and I'll try to be more consistent in the future

**Comment by goldingn** [comment]
btw the style is defined [here](https://github.com/zoonproject/zoon#notes-for-collaborators)

**Comment by AugustT** [comment]
Thanks! However also see:

    Place a space before left parenthesis, except in a function call.

    GOOD: 
    if (debug)

    BAD: 
    if(debug)

Now I know!

**Comment by timcdlucas** [comment]
I might have easily  missed spaces after `if` statements. I just think of if as a function... which maybe it isn't.

**Comment by goldingn** [comment]
Yeah, it's a bit tricky. From ``?`if` ``:

>These are the basic control-flow constructs of the R language.

which implies it's not a function call ... and from ``?`function` ``:

>These functions provide the base mechanisms for defining new functions in the R language.

which implies this one is. 

``?`stop` `` is less clear though:
>`stop` stops execution of the current expression and executes an error action.

Not that any of this has serious consequences

**Comment by goldingn** [comment]
closing this because it's neither an issue nor being discussed any more
