### ISSUE TITLE
SurfaceMap cannot start png() device

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#99]
Running this I get an error
```R
sdm <- workflow(SpOcc(species = 'Eresus sandaliatus', extent = c(-10, 45, 10, 65), databases = 'gbif'), 
                Bioclim(extent = c(-10, 45, 10, 65)), 
                OneHundredBackground, 
                BiomodModel(modelType = c('GLM')), 
                SurfaceMap
)
```

Error:
```
Caught errors:
Error in png(paste0(dir, "/ZoonMap", Sys.time(), ".png")): unable to start png() device
```

And here is the traceback
```
7 stop(x, call. = FALSE) at zoonHelpers.R#447
6 ErrorAndSave(cond, 5, e) at zoon.R#210
5 value[[3L]](cond) 
4 tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
3 tryCatchList(expr, classes, parentenv, handlers) 
2 tryCatch({
    output.output <- DoOutputModules(output.module, outputName, 
        covariate.module, covariate.output, model.output, e)
}, error = function(cond) { ... at zoon.R#205
1 workflow(SpOcc(species = "Eresus sandaliatus", extent = c(-10, 
    45, 10, 65), databases = "gbif"), Bioclim(extent = c(-10, 
    45, 10, 65)), OneHundredBackground, BiomodModel(modelType = c("GLM")), 
    SurfaceMap) 
```

**Comment by timcdlucas** [comment]
Had a load of package conflicts. But this works for me in a clean R session.

Sounds like a operating system problem (do you use windows by the way? Or something else.)

Does just a normal png() call work?

**Comment by AugustT** [comment]
I'm using windows. Other than the above png() is working as expected.

**Comment by timcdlucas** [comment]
Ah, Sys.time() gives the time with colons.
    1> paste0(dir,"/ZoonMap", Sys.time(), ".png")
    [1] "./ZoonMap2015-08-19 14:45:20.png"

Windows doesn't allow colons so this will need a reformat. I'll do it as I'm here.

**Comment by AugustT** [comment]
Boom, was literally about to ask if your filename had a colon in it.

I was going to replace with 
```R
format(Sys.time(), "%d_%m_%Y")
```

**Comment by AugustT** [comment]
On second thoughts best to include the time as well to avoid overwriting the file.

**Comment by timcdlucas** [comment]
Yeah, that's why I put the time in. Just struggling to find something that is useful. format(Sys.time(), "%y-%m-%d_%H-%M") is quite hard to see that it's even a datetime.

**Comment by AugustT** [comment]
How about

```R
format(Sys.time(), "%Y-%m-%d_%Hhr%Mmin") 
```

**Comment by timcdlucas** [comment]
I went for "%Y_%m_%d-%H%M%. Think it's alright. 

Fixed by cdafef3eb972303dc795d33e008c5d513671cabd

**Comment by AugustT** [comment]
Hi @timcdlucas 

Can you put in a pull request for this change?

Tom

**Comment by timcdlucas** [comment]
I put in the PR when I made the changes. 
https://github.com/zoonproject/modules/pull/15

(it's in zoonproject/modules not zoonproject/zoon, even though this issue is in zoonproject/zoon.)

**Comment by AugustT** [comment]
Got it. Sorry, I thought you would have merged it straight away. Don't feel that I need to approve your merges :)

**Comment by timcdlucas** [comment]
Hmmm.... just wonder whether it's better to let you do it so there's some central control. Especially when there's lots of activity. I'll accept them if I'm confident it's wanted etc.

**Comment by AugustT** [comment]
Sure, I'm happy to do the majority but with something like this where the change is small and it closes an issue I say 'fire away!'
